In [1]:
# !pip install transformers accelerate
from transformers import EarlyStoppingCallback
import torch
import numpy as np
import pandas as pd
# !pip install datasets
from datasets import Dataset
# %pip install evaluate
import evaluate
from sklearn.model_selection import train_test_split
# from ipywidgets import FloatProgress
import csv
from optuna import Trial
from typing import Dict, Union, Any
import os
import sys

# notebook_login()

csv.field_size_limit(500 * 1024 * 1024)
CUDA_LAUNCH_BLOCKING=1
# get pwd
notebook_path = os.path.abspath('')

# Find the part of the path that contains 'commitFit'
commit_fit_path = None
for part in notebook_path.split(os.sep):
    print(part)
    if 'CommitFit' in part:
        commit_fit_path = notebook_path.split(part)[0] + part
        break

if commit_fit_path is None:
    raise ValueError("Path containing 'commitFit' not found in notebook path.")

# Add commitFit directory to Python path, so we can import moudule from commitfit folder directly
if commit_fit_path not in sys.path:
    sys.path.append(commit_fit_path)

from commitfit import CommitFitModel, CommitFitTrainer 
from commitfit import get_templated_dataset,sample_dataset


root
autodl-tmp
CommitFit


In [2]:
df = pd.read_csv(r'/root/autodl-tmp/CommitFit/dataset/Ghadhab/dataset.csv', index_col=0, encoding='utf_8_sig')
# df.fillna('', inplace=True)
label2id={'C':0, 'A':1, 'P':2}
df = df.rename(columns={'labels':'label','msgs':'text','commit_diff':'diffs'})
df = df.replace({"label": label2id})
# # print(df)
df
# test_sample = df.sample(n=3, random_state=1)

repo                                    commit  \
user                                                                     
ponsonio              RxJava  0531b8bff5c14d9504beefb4ad47f473e3a22932   
ponsonio              RxJava  0950c46beda335819928585f1262dfe1dca78a0b   
ponsonio              RxJava  0f92fdd8e6422d5b79c610a7fd8409d222315a49   
ponsonio              RxJava  100f571c9a2835d5a30a55374b9be74c147e031f   
ponsonio              RxJava  191f023cf5253ea90647bc091dcaf55ccdce81cc   
...                      ...                                       ...   
jenkinsci   clearcase-plugin  51e9da224f80254476a7dc446bca817b505381d8   
jexp            batch-import  609d6c4b1eea2c33d9fb950fcbb9ba9dc1f80fc3   
hdiv                    hdiv  19b650c78a1c76f4fd90274d7f163f863c0d39e4   
casidiablo       persistence  d7bf95159df37a3d338ca267dddd3d26b38ec37c   
jhy                    jsoup  d6fd1637307f6b088eb226c3f979085725530f32   

                 label                                               text  \
user                                                                        
ponsonio    Perfective              Change hasException to hasThrowable--   
ponsonio      Adaptive  Trying to extend the Scheduler interface accor...   
ponsonio      Adaptive   RunAsync method for outputting multiple values--   
ponsonio    Corrective  forEach with Action1 but not Observer--I re-re...   
ponsonio    Corrective  1.x: Fix Completable swallows- OnErrorNotImple...   
...                ...                                                ...   
jenkinsci   Perfective  Use a temporary file to decrease memory consum...   
jexp        Perfective  added a more memory efficient structure for st...   
hdiv        Perfective               Memory and performance optimizations   
casidiablo  Perfective  Now it is possible to specify the sqlite open ...   
jhy         Perfective            Performance improvment for Element.text   

                                                        diffs  \
user                                                            
ponsonio    diff --git a/rxjava-core/src/main/java/rx/Noti...   
ponsonio    diff --git a/rxjava-core/src/main/java/rx/Sche...   
ponsonio    diff --git a/rxjava-contrib/rxjava-async-util/...   
ponsonio    diff --git a/language-adaptors/rxjava-groovy/s...   
ponsonio    diff --git a/src/main/java/rx/Completable.java...   
...                                                       ...   
jenkinsci   diff --git a/src/main/java/hudson/plugins/clea...   
jexp        diff --git a/src/main/java/org/neo4j/batchimpo...   
hdiv        diff --git a/hdiv-config/src/main/java/org/hdi...   
casidiablo  diff --git a/pom.xml b/pom.xml\nindex 394263b....   
jhy         diff --git a/src/main/java/org/jsoup/helper/St...   

                                                      feature  
user                                                           
ponsonio    [1, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
ponsonio    [2, 44, 0, 0, 30, 0, 0, 1, 18, 0, 0, 0, 0, 0, ...  
ponsonio    [2, 53, 0, 0, 42, 0, 0, 1, 45, 1, 0, 0, 0, 0, ...  
ponsonio    [1, 5, 122, 9, 10, 9, 4, 1, 5, 18, 2, 0, 0, 0,...  
ponsonio    [1, 1, 0, 0, 0, 0, 0, 1, 21, 0, 0, 0, 0, 0, 0,...  
...                                                       ...  
jenkinsci   [2, 12, 0, 4, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,...  
jexp        [10, 159, 29, 35, 9, 2, 1, 5, 106, 0, 4, 8, 0,...  
hdiv        [31, 302, 131, 140, 170, 89, 53, 7, 88, 14, 17...  
casidiablo  [5, 57, 20, 9, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
jhy         [3, 11, 11, 9, 13, 0, 0, 1, 0, 8, 0, 0, 1, 0, ...  

[1781 rows x 6 columns]

In [3]:
train, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val, test = train_test_split(temp_df, test_size=0.5, random_state=42)

In [4]:
train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=5, random_state=42))

/tmp/ipykernel_5353/2882598814.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=5, random_state=42))


In [5]:
# train.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/5_train.csv')
# test.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/test.csv')
# val.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/val.csv')

# train.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/5_train.csv')
# test.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/test.csv')
# val.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/val.csv')

In [6]:
Dataset_train = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

In [7]:
train_dataset = get_templated_dataset(Dataset_train, candidate_labels=['Corrective','Adaptive','Perfective'], sample_size=8)

In [8]:
train_code_change = list(train['diffs'].astype(str))
test_code_change = list(test['diffs'].astype(str))

In [9]:
# list(train['message'].astype(str).values)
train_dataset

Dataset({
    features: ['repo', 'commit', 'label', 'text', 'diffs', 'feature', 'user'],
    num_rows: 39
})

In [10]:
len(train)

15

In [11]:
train['label'].value_counts()

label
Adaptive      5
Corrective    5
Perfective    5
Name: count, dtype: int64

In [12]:
test['label'].value_counts()

label
Perfective    100
Corrective     89
Adaptive       79
Name: count, dtype: int64

In [13]:
len(train_dataset)

39

In [14]:
from sklearn import  metrics

def compute_metrics(y_pred, y_test):
    # print(y_pred,y_test)
    # classification_report = metrics.classification_report(y_test,y_pred)
    accuracy_score = metrics.accuracy_score(y_test,y_pred)
    precision_score = metrics.precision_score(y_test,y_pred, average='macro')
    recall_score = metrics.recall_score(y_test,y_pred,average='macro')
    f1_score = metrics.f1_score(y_test,y_pred,average='macro')
    
    # 混淆矩阵
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:\n", cm)
    print(metrics.classification_report(y_test, y_pred, digits=4))
    # return {"classification_report": classification_report}
    return {"classification_report":metrics.classification_report(y_test, y_pred, digits=4),"Confusion Matrix":cm,"precision": round(precision_score, 4),"recall": round(recall_score, 4), "f1":round(f1_score, 4), "accuracy": round(accuracy_score, 4)}

In [15]:
train_dataset

Dataset({
    features: ['repo', 'commit', 'label', 'text', 'diffs', 'feature', 'user'],
    num_rows: 39
})

In [16]:
model_id = "../../sentence-transformers/paraphrase-mpnet-base-v2"

In [17]:
def hp_space(trial: Trial) -> Dict[str, Union[float, int, str]]:
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-3, log=True),
        # "num_epochs": trial.suggest_int("num_epochs", 1, 3),
        # "batch_size": trial.suggest_categorical("batch_size", [8, 12, 16]),
        # "seed": trial.suggest_int("seed", 1, 40),
        # "num_iterations": trial.suggest_int("num_iterations", 10, 20),
        # "solver": trial.suggest_categorical("solver", ["newton-cg", "lbfgs", "liblinear"]),
    }
def model_init(params: Dict[str, Any]) -> CommitFitModel:
    params = params or {}
    # learning_rate = params.get("learning_rate")
    # num_iterations = params.get("num_iterations", 20)
    # solver = params.get("solver", "liblinear")
    # params = {
    #     "head_params": {
    #         # "max_iter": num_iterations,
    #         # "solver": solver,
    #     }
    # }
    return CommitFitModel.from_pretrained(model_id, **params)
def my_compute_objective(metrics):
    print('+++++++++++',metrics)
    return  metrics['accuracy']

In [18]:
trainer = CommitFitTrainer(
    train_dataset=train_dataset,
    train_code_change = train_code_change,
    test_code_change = test_code_change,
    eval_dataset=test_dataset,
    model_init=model_init,
    metric = compute_metrics,
    num_iterations=20,
    num_epochs=1
)
best_run = trainer.hyperparameter_search(direction="maximize", hp_space=hp_space, compute_objective=my_compute_objective, n_trials=10)

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
[I 2025-08-28 21:48:38,138] A new study created in memory with name: no-name-174458bd-6276-410e-b7ab-5def0506e03d
Trial: {'learning_rate': 0.00042624742897386315}
model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix:
 [[ 0 24 55]
 [ 0 37 52]
 [ 0 31 69]]
              precision    recall  f1-score   support

    Adaptive     0.0000    0.0000    0.0000        79
  Corrective     0.4022    0.4157    0.4088        89
  Perfective     0.3920    0.6900    0.5000       100

    accuracy                         0.3955       268
   macro avg     0.2647    0.3686    0.3029       268
weighted avg     0.2798    0.3955    0.3223       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.0000    0.0000    0.0000        79\n  Corrective     0.4022    0.4157    0.4088        89\n  Perfective     0.3920    0.6900    0.5000       100\n\n    accuracy                         0.3955       268\n   macro avg     0.2647    0.3686    0.3029       268\nweighted avg     0.2798    0.3955    0.3223       268\n', 'Confusion Matrix': array([[ 0, 24, 55],
       [ 0, 37, 52],
       [ 0, 31, 69]]), 'precision': 0.2647, 'recall': 0.3686, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:49:11,875] Trial 1 finished with value: 0.7052 and parameters: {'learning_rate': 8.149349746090063e-05}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 7.839217735825806e-05}


Confusion Matrix:
 [[48  7 24]
 [ 9 68 12]
 [19  8 73]]
              precision    recall  f1-score   support

    Adaptive     0.6316    0.6076    0.6194        79
  Corrective     0.8193    0.7640    0.7907        89
  Perfective     0.6697    0.7300    0.6986       100

    accuracy                         0.7052       268
   macro avg     0.7069    0.7005    0.7029       268
weighted avg     0.7081    0.7052    0.7058       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.6316    0.6076    0.6194        79\n  Corrective     0.8193    0.7640    0.7907        89\n  Perfective     0.6697    0.7300    0.6986       100\n\n    accuracy                         0.7052       268\n   macro avg     0.7069    0.7005    0.7029       268\nweighted avg     0.7081    0.7052    0.7058       268\n', 'Confusion Matrix': array([[48,  7, 24],
       [ 9, 68, 12],
       [19,  8, 73]]), 'precision': 0.7069, 'recall': 0.7005, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:49:28,281] Trial 2 finished with value: 0.6978 and parameters: {'learning_rate': 7.839217735825806e-05}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 1.9135728293266137e-05}


Confusion Matrix:
 [[49  6 24]
 [ 8 65 16]
 [19  8 73]]
              precision    recall  f1-score   support

    Adaptive     0.6447    0.6203    0.6323        79
  Corrective     0.8228    0.7303    0.7738        89
  Perfective     0.6460    0.7300    0.6854       100

    accuracy                         0.6978       268
   macro avg     0.7045    0.6935    0.6972       268
weighted avg     0.7043    0.6978    0.6991       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.6447    0.6203    0.6323        79\n  Corrective     0.8228    0.7303    0.7738        89\n  Perfective     0.6460    0.7300    0.6854       100\n\n    accuracy                         0.6978       268\n   macro avg     0.7045    0.6935    0.6972       268\nweighted avg     0.7043    0.6978    0.6991       268\n', 'Confusion Matrix': array([[49,  6, 24],
       [ 8, 65, 16],
       [19,  8, 73]]), 'precision': 0.7045, 'recall': 0.6935, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:49:44,375] Trial 3 finished with value: 0.6716 and parameters: {'learning_rate': 1.9135728293266137e-05}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 3.503634476721935e-05}


Confusion Matrix:
 [[54 10 15]
 [19 63  7]
 [32  5 63]]
              precision    recall  f1-score   support

    Adaptive     0.5143    0.6835    0.5870        79
  Corrective     0.8077    0.7079    0.7545        89
  Perfective     0.7412    0.6300    0.6811       100

    accuracy                         0.6716       268
   macro avg     0.6877    0.6738    0.6742       268
weighted avg     0.6964    0.6716    0.6777       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5143    0.6835    0.5870        79\n  Corrective     0.8077    0.7079    0.7545        89\n  Perfective     0.7412    0.6300    0.6811       100\n\n    accuracy                         0.6716       268\n   macro avg     0.6877    0.6738    0.6742       268\nweighted avg     0.6964    0.6716    0.6777       268\n', 'Confusion Matrix': array([[54, 10, 15],
       [19, 63,  7],
       [32,  5, 63]]), 'precision': 0.6877, 'recall': 0.6738, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:50:00,329] Trial 4 finished with value: 0.6791 and parameters: {'learning_rate': 3.503634476721935e-05}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 1.1673895265446174e-06}


Confusion Matrix:
 [[50 10 19]
 [ 9 68 12]
 [30  6 64]]
              precision    recall  f1-score   support

    Adaptive     0.5618    0.6329    0.5952        79
  Corrective     0.8095    0.7640    0.7861        89
  Perfective     0.6737    0.6400    0.6564       100

    accuracy                         0.6791       268
   macro avg     0.6817    0.6790    0.6793       268
weighted avg     0.6858    0.6791    0.6815       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5618    0.6329    0.5952        79\n  Corrective     0.8095    0.7640    0.7861        89\n  Perfective     0.6737    0.6400    0.6564       100\n\n    accuracy                         0.6791       268\n   macro avg     0.6817    0.6790    0.6793       268\nweighted avg     0.6858    0.6791    0.6815       268\n', 'Confusion Matrix': array([[50, 10, 19],
       [ 9, 68, 12],
       [30,  6, 64]]), 'precision': 0.6817, 'recall': 0.679, 'f1': 0.6

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:50:16,508] Trial 5 finished with value: 0.597 and parameters: {'learning_rate': 1.1673895265446174e-06}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 3.939368518447774e-05}


Confusion Matrix:
 [[41 16 22]
 [11 53 25]
 [19 15 66]]
              precision    recall  f1-score   support

    Adaptive     0.5775    0.5190    0.5467        79
  Corrective     0.6310    0.5955    0.6127        89
  Perfective     0.5841    0.6600    0.6197       100

    accuracy                         0.5970       268
   macro avg     0.5975    0.5915    0.5930       268
weighted avg     0.5977    0.5970    0.5959       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5775    0.5190    0.5467        79\n  Corrective     0.6310    0.5955    0.6127        89\n  Perfective     0.5841    0.6600    0.6197       100\n\n    accuracy                         0.5970       268\n   macro avg     0.5975    0.5915    0.5930       268\nweighted avg     0.5977    0.5970    0.5959       268\n', 'Confusion Matrix': array([[41, 16, 22],
       [11, 53, 25],
       [19, 15, 66]]), 'precision': 0.5975, 'recall': 0.5915, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:50:32,697] Trial 6 finished with value: 0.6791 and parameters: {'learning_rate': 3.939368518447774e-05}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 1.499936577942681e-05}


Confusion Matrix:
 [[49 10 20]
 [ 9 67 13]
 [28  6 66]]
              precision    recall  f1-score   support

    Adaptive     0.5698    0.6203    0.5939        79
  Corrective     0.8072    0.7528    0.7791        89
  Perfective     0.6667    0.6600    0.6633       100

    accuracy                         0.6791       268
   macro avg     0.6812    0.6777    0.6788       268
weighted avg     0.6848    0.6791    0.6813       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5698    0.6203    0.5939        79\n  Corrective     0.8072    0.7528    0.7791        89\n  Perfective     0.6667    0.6600    0.6633       100\n\n    accuracy                         0.6791       268\n   macro avg     0.6812    0.6777    0.6788       268\nweighted avg     0.6848    0.6791    0.6813       268\n', 'Confusion Matrix': array([[49, 10, 20],
       [ 9, 67, 13],
       [28,  6, 66]]), 'precision': 0.6812, 'recall': 0.6777, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:50:48,911] Trial 7 finished with value: 0.6866 and parameters: {'learning_rate': 1.499936577942681e-05}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 0.00013894726605638054}


Confusion Matrix:
 [[51  9 19]
 [15 63 11]
 [25  5 70]]
              precision    recall  f1-score   support

    Adaptive     0.5604    0.6456    0.6000        79
  Corrective     0.8182    0.7079    0.7590        89
  Perfective     0.7000    0.7000    0.7000       100

    accuracy                         0.6866       268
   macro avg     0.6929    0.6845    0.6863       268
weighted avg     0.6981    0.6866    0.6901       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5604    0.6456    0.6000        79\n  Corrective     0.8182    0.7079    0.7590        89\n  Perfective     0.7000    0.7000    0.7000       100\n\n    accuracy                         0.6866       268\n   macro avg     0.6929    0.6845    0.6863       268\nweighted avg     0.6981    0.6866    0.6901       268\n', 'Confusion Matrix': array([[51,  9, 19],
       [15, 63, 11],
       [25,  5, 70]]), 'precision': 0.6929, 'recall': 0.6845, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:51:04,679] Trial 8 finished with value: 0.4403 and parameters: {'learning_rate': 0.00013894726605638054}. Best is trial 1 with value: 0.7052.
Trial: {'learning_rate': 0.00014860242751065232}


Confusion Matrix:
 [[38 33  8]
 [27 50 12]
 [42 28 30]]
              precision    recall  f1-score   support

    Adaptive     0.3551    0.4810    0.4086        79
  Corrective     0.4505    0.5618    0.5000        89
  Perfective     0.6000    0.3000    0.4000       100

    accuracy                         0.4403       268
   macro avg     0.4685    0.4476    0.4362       268
weighted avg     0.4782    0.4403    0.4357       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.3551    0.4810    0.4086        79\n  Corrective     0.4505    0.5618    0.5000        89\n  Perfective     0.6000    0.3000    0.4000       100\n\n    accuracy                         0.4403       268\n   macro avg     0.4685    0.4476    0.4362       268\nweighted avg     0.4782    0.4403    0.4357       268\n', 'Confusion Matrix': array([[38, 33,  8],
       [27, 50, 12],
       [42, 28, 30]]), 'precision': 0.4685, 'recall': 0.4476, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-28 21:51:20,653] Trial 9 finished with value: 0.5933 and parameters: {'learning_rate': 0.00014860242751065232}. Best is trial 1 with value: 0.7052.


Confusion Matrix:
 [[58 10 11]
 [13 67  9]
 [52 14 34]]
              precision    recall  f1-score   support

    Adaptive     0.4715    0.7342    0.5743        79
  Corrective     0.7363    0.7528    0.7444        89
  Perfective     0.6296    0.3400    0.4416       100

    accuracy                         0.5933       268
   macro avg     0.6125    0.6090    0.5868       268
weighted avg     0.6184    0.5933    0.5813       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4715    0.7342    0.5743        79\n  Corrective     0.7363    0.7528    0.7444        89\n  Perfective     0.6296    0.3400    0.4416       100\n\n    accuracy                         0.5933       268\n   macro avg     0.6125    0.6090    0.5868       268\nweighted avg     0.6184    0.5933    0.5813       268\n', 'Confusion Matrix': array([[58, 10, 11],
       [13, 67,  9],
       [52, 14, 34]]), 'precision': 0.6125, 'recall': 0.609, 'f1': 0.5

In [19]:
# best_run

In [20]:
best_run.hyperparameters

{'learning_rate': 8.149349746090063e-05}

In [21]:
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 1
  Total optimization steps = 98
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/98 [00:00<?, ?it/s]

In [25]:
fewshot_metrics = trainer.evaluate()
fewshot_metrics

***** Running evaluation *****


Confusion Matrix:
 [[54  6 19]
 [22 42 25]
 [43  3 54]]
              precision    recall  f1-score   support

    Adaptive     0.4538    0.6835    0.5455        79
  Corrective     0.8235    0.4719    0.6000        89
  Perfective     0.5510    0.5400    0.5455       100

    accuracy                         0.5597       268
   macro avg     0.6094    0.5652    0.5636       268
weighted avg     0.6129    0.5597    0.5636       268



{'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4538    0.6835    0.5455        79\n  Corrective     0.8235    0.4719    0.6000        89\n  Perfective     0.5510    0.5400    0.5455       100\n\n    accuracy                         0.5597       268\n   macro avg     0.6094    0.5652    0.5636       268\nweighted avg     0.6129    0.5597    0.5636       268\n',
 'Confusion Matrix': array([[54,  6, 19],
        [22, 42, 25],
        [43,  3, 54]]),
 'precision': 0.6094,
 'recall': 0.5652,
 'f1': 0.5636,
 'accuracy': 0.5597}

In [23]:
#发送多种类型的邮件
from email.mime.multipart import MIMEMultipart
import smtplib

from email.mime.text import MIMEText
msg_from = '915803745@qq.com'  # 发送方邮箱
passwd = 'vcuosuurrgkfbdai'   #就是上面的授权码
 
# to= ['g.zhang@gotion.com', 'j.tong@gotion.com'] #接受方邮箱
to= ['j.tong@gotion.com'] #接受方邮箱
#设置邮件内容
#MIMEMultipart类可以放任何内容
msg = MIMEMultipart()
conntent=f"{fewshot_metrics}"
#把内容加进去
msg.attach(MIMEText(conntent,'plain','utf-8'))
 
#设置邮件主题
msg['Subject']="强化学习模型训练完毕"
 
#发送方信息
msg['From']=msg_from
 
#开始发送
 
#通过SSL方式发送，服务器地址和端口
s = smtplib.SMTP_SSL("smtp.qq.com", 465)
# 登录邮箱
s.login(msg_from, passwd)
#开始发送
s.sendmail(msg_from,to,msg.as_string())
print("强化学习模型训练完毕")

强化学习模型训练完毕
