In [1]:
# !pip install transformers accelerate
# from transformers import AutoTokenizer, AutoModel, EarlyStoppingCallback, AutoModelForSequenceClassification, AutoConfig,Trainer, TrainingArguments,DataCollatorWithPadding
import torch
import numpy as np
import pandas as pd
# !pip install datasets
from datasets import Dataset
# %pip install evaluate
import evaluate
from sklearn.model_selection import train_test_split
# from ipywidgets import FloatProgress
import csv
from optuna import Trial
from typing import Dict, Union, Any
import os
import sys

# notebook_login()

csv.field_size_limit(500 * 1024 * 1024)
CUDA_LAUNCH_BLOCKING=1
# get pwd
notebook_path = os.path.abspath('')

# Find the part of the path that contains 'commitFit'
commit_fit_path = None
for part in notebook_path.split(os.sep):
    print(part)
    if 'CommitFit' in part:
        commit_fit_path = notebook_path.split(part)[0] + part
        break

if commit_fit_path is None:
    raise ValueError("Path containing 'commitFit' not found in notebook path.")

# Add commitFit directory to Python path, so we can import moudule from commitfit folder directly
if commit_fit_path not in sys.path:
    sys.path.append(commit_fit_path)

from commitfit import CommitFitModel, CommitFitTrainer 
from commitfit import get_templated_dataset,sample_dataset


root
autodl-tmp
CommitFit


In [2]:
df = pd.read_csv(r'/root/autodl-tmp/CommitFit/dataset/multi-lang-annotated/dataset.csv', index_col=0, encoding='utf_8_sig')
# df.fillna('', inplace=True)
label2id={'C':0, 'A':1, 'P':2}
# df.reset_index(inplace=True)
df = df.rename(columns={'maintenance_type':'label','commit_message':'text','commit_diff':'diffs'})
df = df.replace({"label": label2id})
# df = df['diffs']
# # print(df)

df
# test_sample = df.sample(n=3, random_state=1)

/tmp/ipykernel_2730/3292594428.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({"label": label2id})


label  \
commit_sha                                        
be937a3290223f926fe50684f1344569a573ed4b      0   
c800d2e36954edddcb83aa1df7f623f2780c7780      1   
469e56eeff17eb857c95e935ca7b49723c43470e      2   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d      1   
1effdb7b959503596b07f7f3e74618ab63f9e5e5      2   
...                                         ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e      0   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3      0   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce      0   
48701edad8513b27acec7216581e64637157c86a      1   
45529d30d41b8de338dfc2d26b61d1a79113c766      1   

                                                                                      diffs  \
commit_sha                                                                                    
be937a3290223f926fe50684f1344569a573ed4b  diff --git a/tensorflow/compiler/mlir/lite/fla...   
c800d2e36954edddcb83aa1df7f623f2780c7780  diff --git a/tensorflow/python/tools/saved_mod...   
469e56eeff17eb857c95e935ca7b49723c43470e  diff --git a/.github/ISSUE_TEMPLATE/00-bug-iss...   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d  diff --git a/tensorflow/compiler/xla/pjrt/dist...   
1effdb7b959503596b07f7f3e74618ab63f9e5e5  diff --git a/tensorflow/core/common_runtime/ea...   
...                                                                                     ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e  diff --git a/drools-persistence-jpa/src/main/j...   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3  diff --git a/drools-compiler/src/main/java/org...   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce  diff --git a/drools-core/src/main/java/org/dro...   
48701edad8513b27acec7216581e64637157c86a  diff --git a/drools-core/src/main/java/org/dro...   
45529d30d41b8de338dfc2d26b61d1a79113c766  diff --git a/drools-compiler/src/test/java/org...   

                                                                                       text  \
commit_sha                                                                                    
be937a3290223f926fe50684f1344569a573ed4b  Fixing per axis quantization bug in flatbuffer...   
c800d2e36954edddcb83aa1df7f623f2780c7780  Add support for python expression as SavedMode...   
469e56eeff17eb857c95e935ca7b49723c43470e  Fix GitHub issue templates. Actual fix for #36...   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d  Add new PjRT distributed APIs (KeyValueDelete,...   
1effdb7b959503596b07f7f3e74618ab63f9e5e5  Remove IsLocalDevice() since it's no longer us...   
...                                                                                     ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e  fixing reflection constructor to use int inste...   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3  Fix OutOfBoundException on- MemoryFileSystem.e...   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce  [DROOLS-293] fix ObjectTypeNode id creation an...   
48701edad8513b27acec7216581e64637157c86a  DROOLS-515 Kie-Camel is broken after Camel Upd...   
45529d30d41b8de338dfc2d26b61d1a79113c766  JBRULES-2934 Add NewRegisterWorkItemHandlerCom...   

                                          CODE_CHANGE_FILE  \
commit_sha                                                   
be937a3290223f926fe50684f1344569a573ed4b                 1   
c800d2e36954edddcb83aa1df7f623f2780c7780                 0   
469e56eeff17eb857c95e935ca7b49723c43470e                 0   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d                 3   
1effdb7b959503596b07f7f3e74618ab63f9e5e5                 1   
...                                                    ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e                 1   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3                 2   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce                 1   
48701edad8513b27acec7216581e64637157c86a                 2   
45529d30d41b8de338dfc2d26b61d1a79113c766                 1   

                                          CODE_ADD_CODE_LINE  \
commit_sha                         

In [3]:
train, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val_df, test = train_test_split(temp_df, test_size=0.5, random_state=42)

In [4]:
train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=5, random_state=42))

/tmp/ipykernel_2730/2882598814.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=5, random_state=42))


In [5]:
# train.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/5_train.csv',index=False)
# test.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/test.csv',index=False)
# val.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/eval.csv',index=False)
# train.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/5_train.csv',index=False)
# test.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/test.csv',index=False)
# val.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/eval.csv',index=False)

In [6]:
Dataset_train = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

In [7]:
train_dataset = get_templated_dataset(Dataset_train, candidate_labels=['Corrective','Adaptive','Perfective'], sample_size=8)

In [8]:
train_code_change = list(train['diffs'].astype(str))
test_code_change = list(test['diffs'].astype(str))

In [9]:
# list(train['message'].astype(str).values)
train_dataset

Dataset({
    features: ['label', 'diffs', 'text', 'CODE_CHANGE_FILE', 'CODE_ADD_CODE_LINE', 'CODE_DEL_CODE_LINE', 'CODE_MOD_CODE_LINE', 'CODE_ADD_COMMENT_LINE', 'CODE_DEL_COMMENT_LINE', 'CODE_MOD_COMMENT_LINE', 'TEST_CHANGE_FILE', 'TEST_ADD_CODE_LINE', 'TEST_DEL_CODE_LINE', 'TEST_MOD_CODE_LINE', 'TEST_ADD_COMMENT_LINE', 'TEST_DEL_COMMENT_LINE', 'TEST_MOD_COMMENT_LINE', 'TEST_ADD_OTHER_LINE', 'TEST_DEL_OTHER_LINE', 'TEST_MOD_OTHER_LINE', 'BUILD_CHANGE_FILE', 'BUILD_ADD_LINE', 'BUILD_DEL_LINE', 'BUILD_MOD_LINE', 'DOC_CHANGE_FILE', 'DOC_ADD_LINE', 'DOC_DEL_LINE', 'DOC_MOD_LINE', 'OTHER_CHANGE_FILE', 'OTHER_ADD_LINE', 'OTHER_DEL_LINE', 'OTHER_MOD_LINE', 'commit_sha'],
    num_rows: 39
})

In [10]:
len(train)

15

In [11]:
train['label'].value_counts()

label
0    5
1    5
2    5
Name: count, dtype: int64

In [12]:
test['label'].value_counts()

label
2    155
0     51
1     32
Name: count, dtype: int64

In [13]:
len(train_dataset)

39

In [14]:
from sklearn import  metrics

def compute_metrics(y_pred, y_test):
    # print(y_pred,y_test)
    # classification_report = metrics.classification_report(y_test,y_pred)
    accuracy_score = metrics.accuracy_score(y_test,y_pred)
    precision_score = metrics.precision_score(y_test,y_pred, average='macro')
    recall_score = metrics.recall_score(y_test,y_pred,average='macro')
    f1_score = metrics.f1_score(y_test,y_pred,average='macro')
    
    # 混淆矩阵
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:\n", cm)
    print(metrics.classification_report(y_test, y_pred, digits=4))
    # return {"classification_report": classification_report}
    return {"classification_report":metrics.classification_report(y_test, y_pred, digits=4),"Confusion Matrix":cm,"precision": round(precision_score, 4),"recall": round(recall_score, 4), "f1":round(f1_score, 4), "accuracy": round(accuracy_score, 4)}

In [15]:
train_dataset

Dataset({
    features: ['label', 'diffs', 'text', 'CODE_CHANGE_FILE', 'CODE_ADD_CODE_LINE', 'CODE_DEL_CODE_LINE', 'CODE_MOD_CODE_LINE', 'CODE_ADD_COMMENT_LINE', 'CODE_DEL_COMMENT_LINE', 'CODE_MOD_COMMENT_LINE', 'TEST_CHANGE_FILE', 'TEST_ADD_CODE_LINE', 'TEST_DEL_CODE_LINE', 'TEST_MOD_CODE_LINE', 'TEST_ADD_COMMENT_LINE', 'TEST_DEL_COMMENT_LINE', 'TEST_MOD_COMMENT_LINE', 'TEST_ADD_OTHER_LINE', 'TEST_DEL_OTHER_LINE', 'TEST_MOD_OTHER_LINE', 'BUILD_CHANGE_FILE', 'BUILD_ADD_LINE', 'BUILD_DEL_LINE', 'BUILD_MOD_LINE', 'DOC_CHANGE_FILE', 'DOC_ADD_LINE', 'DOC_DEL_LINE', 'DOC_MOD_LINE', 'OTHER_CHANGE_FILE', 'OTHER_ADD_LINE', 'OTHER_DEL_LINE', 'OTHER_MOD_LINE', 'commit_sha'],
    num_rows: 39
})

In [16]:
model_id = "../../sentence-transformers/paraphrase-mpnet-base-v2"

In [17]:
def hp_space(trial: Trial) -> Dict[str, Union[float, int, str]]:
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-3, log=True),
        # "num_epochs": trial.suggest_int("num_epochs", 1, 3),
        # "batch_size": trial.suggest_categorical("batch_size", [8, 12, 16]),
        # "seed": trial.suggest_int("seed", 1, 40),
        # "num_iterations": trial.suggest_int("num_iterations", 10, 20),
        # "solver": trial.suggest_categorical("solver", ["newton-cg", "lbfgs", "liblinear"]),
    }
def model_init(params: Dict[str, Any]) -> CommitFitModel:
    params = params or {}
    # learning_rate = params.get("learning_rate")
    # num_iterations = params.get("num_iterations", 20)
    # solver = params.get("solver", "liblinear")
    # params = {
    #     "head_params": {
    #         # "max_iter": num_iterations,
    #         # "solver": solver,
    #     }
    # }
    return CommitFitModel.from_pretrained(model_id, **params)
def my_compute_objective(metrics):
    print('+++++++++++',metrics)
    return  metrics['accuracy']

In [18]:
trainer = CommitFitTrainer(
    train_dataset=train_dataset,
    train_code_change = train_code_change,
    test_code_change = test_code_change,
    eval_dataset=test_dataset,
    model_init=model_init,
    metric = compute_metrics,
    num_iterations=20,
    num_epochs=10,
    batch_size = 32
)
best_run = trainer.hyperparameter_search(direction="maximize", hp_space=hp_space, compute_objective=my_compute_objective, n_trials=5)

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
[I 2025-12-11 17:08:38,355] A new study created in memory with name: no-name-97afc943-0c40-4f21-a045-218ddca4e134
Trial: {'learning_rate': 5.433312700901123e-05}
model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 10
  Total optimization steps = 490
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 17:09:38,312] Trial 0 finished with value: 0.5168 and parameters: {'learning_rate': 5.433312700901123e-05}. Best is trial 0 with value: 0.5168.
Trial: {'learning_rate': 3.3561602852365843e-06}


Confusion Matrix:
 [[38  4  9]
 [ 2 24  6]
 [48 46 61]]
              precision    recall  f1-score   support

           0     0.4318    0.7451    0.5468        51
           1     0.3243    0.7500    0.4528        32
           2     0.8026    0.3935    0.5281       155

    accuracy                         0.5168       238
   macro avg     0.5196    0.6295    0.5092       238
weighted avg     0.6589    0.5168    0.5220       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4318    0.7451    0.5468        51\n           1     0.3243    0.7500    0.4528        32\n           2     0.8026    0.3935    0.5281       155\n\n    accuracy                         0.5168       238\n   macro avg     0.5196    0.6295    0.5092       238\nweighted avg     0.6589    0.5168    0.5220       238\n', 'Confusion Matrix': array([[38,  4,  9],
       [ 2, 24,  6],
       [48, 46, 61]]), 'precision': 0.5196, 'recall': 0.6295, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 10
  Total optimization steps = 490
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 17:10:37,584] Trial 1 finished with value: 0.5168 and parameters: {'learning_rate': 3.3561602852365843e-06}. Best is trial 0 with value: 0.5168.
Trial: {'learning_rate': 0.00011449407014465224}


Confusion Matrix:
 [[37  3 11]
 [ 1 23  8]
 [46 46 63]]
              precision    recall  f1-score   support

           0     0.4405    0.7255    0.5481        51
           1     0.3194    0.7188    0.4423        32
           2     0.7683    0.4065    0.5316       155

    accuracy                         0.5168       238
   macro avg     0.5094    0.6169    0.5074       238
weighted avg     0.6377    0.5168    0.5232       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4405    0.7255    0.5481        51\n           1     0.3194    0.7188    0.4423        32\n           2     0.7683    0.4065    0.5316       155\n\n    accuracy                         0.5168       238\n   macro avg     0.5094    0.6169    0.5074       238\nweighted avg     0.6377    0.5168    0.5232       238\n', 'Confusion Matrix': array([[37,  3, 11],
       [ 1, 23,  8],
       [46, 46, 63]]), 'precision': 0.5094, 'recall': 0.6169, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 10
  Total optimization steps = 490
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 17:11:37,721] Trial 2 finished with value: 0.5336 and parameters: {'learning_rate': 0.00011449407014465224}. Best is trial 2 with value: 0.5336.
Trial: {'learning_rate': 3.198938930592917e-06}


Confusion Matrix:
 [[39  4  8]
 [ 4 21  7]
 [46 42 67]]
              precision    recall  f1-score   support

           0     0.4382    0.7647    0.5571        51
           1     0.3134    0.6562    0.4242        32
           2     0.8171    0.4323    0.5654       155

    accuracy                         0.5336       238
   macro avg     0.5229    0.6177    0.5156       238
weighted avg     0.6682    0.5336    0.5447       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4382    0.7647    0.5571        51\n           1     0.3134    0.6562    0.4242        32\n           2     0.8171    0.4323    0.5654       155\n\n    accuracy                         0.5336       238\n   macro avg     0.5229    0.6177    0.5156       238\nweighted avg     0.6682    0.5336    0.5447       238\n', 'Confusion Matrix': array([[39,  4,  8],
       [ 4, 21,  7],
       [46, 42, 67]]), 'precision': 0.5229, 'recall': 0.6177, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 10
  Total optimization steps = 490
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 17:12:37,166] Trial 3 finished with value: 0.5168 and parameters: {'learning_rate': 3.198938930592917e-06}. Best is trial 2 with value: 0.5336.
Trial: {'learning_rate': 1.2203195070937107e-05}


Confusion Matrix:
 [[37  3 11]
 [ 1 23  8]
 [47 45 63]]
              precision    recall  f1-score   support

           0     0.4353    0.7255    0.5441        51
           1     0.3239    0.7188    0.4466        32
           2     0.7683    0.4065    0.5316       155

    accuracy                         0.5168       238
   macro avg     0.5092    0.6169    0.5075       238
weighted avg     0.6372    0.5168    0.5229       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4353    0.7255    0.5441        51\n           1     0.3239    0.7188    0.4466        32\n           2     0.7683    0.4065    0.5316       155\n\n    accuracy                         0.5168       238\n   macro avg     0.5092    0.6169    0.5075       238\nweighted avg     0.6372    0.5168    0.5229       238\n', 'Confusion Matrix': array([[37,  3, 11],
       [ 1, 23,  8],
       [47, 45, 63]]), 'precision': 0.5092, 'recall': 0.6169, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 10
  Total optimization steps = 490
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 17:13:36,688] Trial 4 finished with value: 0.5294 and parameters: {'learning_rate': 1.2203195070937107e-05}. Best is trial 2 with value: 0.5336.


Confusion Matrix:
 [[38  3 10]
 [ 1 23  8]
 [45 45 65]]
              precision    recall  f1-score   support

           0     0.4524    0.7451    0.5630        51
           1     0.3239    0.7188    0.4466        32
           2     0.7831    0.4194    0.5462       155

    accuracy                         0.5294       238
   macro avg     0.5198    0.6277    0.5186       238
weighted avg     0.6505    0.5294    0.5364       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4524    0.7451    0.5630        51\n           1     0.3239    0.7188    0.4466        32\n           2     0.7831    0.4194    0.5462       155\n\n    accuracy                         0.5294       238\n   macro avg     0.5198    0.6277    0.5186       238\nweighted avg     0.6505    0.5294    0.5364       238\n', 'Confusion Matrix': array([[38,  3, 10],
       [ 1, 23,  8],
       [45, 45, 65]]), 'precision': 0.5198, 'recall': 0.6277, 'f1': 0.

In [19]:
best_run

BestRun(run_id='2', objective=0.5336, hyperparameters={'learning_rate': 0.00011449407014465224}, backend=<optuna.study.study.Study object at 0x7f8a896aec80>)

In [20]:
best_run.hyperparameters

{'learning_rate': 0.00011449407014465224}

In [21]:
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1560
  Num epochs = 10
  Total optimization steps = 490
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

Iteration:   0%|          | 0/49 [00:00<?, ?it/s]

In [22]:
fewshot_metrics = trainer.evaluate()
fewshot_metrics

***** Running evaluation *****


Confusion Matrix:
 [[38  4  9]
 [ 4 21  7]
 [45 41 69]]
              precision    recall  f1-score   support

           0     0.4368    0.7451    0.5507        51
           1     0.3182    0.6562    0.4286        32
           2     0.8118    0.4452    0.5750       155

    accuracy                         0.5378       238
   macro avg     0.5222    0.6155    0.5181       238
weighted avg     0.6650    0.5378    0.5501       238



{'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4368    0.7451    0.5507        51\n           1     0.3182    0.6562    0.4286        32\n           2     0.8118    0.4452    0.5750       155\n\n    accuracy                         0.5378       238\n   macro avg     0.5222    0.6155    0.5181       238\nweighted avg     0.6650    0.5378    0.5501       238\n',
 'Confusion Matrix': array([[38,  4,  9],
        [ 4, 21,  7],
        [45, 41, 69]]),
 'precision': 0.5222,
 'recall': 0.6155,
 'f1': 0.5181,
 'accuracy': 0.5378}

In [23]:
#发送多种类型的邮件
from email.mime.multipart import MIMEMultipart
import smtplib

from email.mime.text import MIMEText
msg_from = '915803745@qq.com'  # 发送方邮箱
passwd = 'vcuosuurrgkfbdai'   #就是上面的授权码
 
# to= ['g.zhang@gotion.com', 'j.tong@gotion.com'] #接受方邮箱
to= ['j.tong@gotion.com'] #接受方邮箱
#设置邮件内容
#MIMEMultipart类可以放任何内容
msg = MIMEMultipart()
conntent=f"{fewshot_metrics}"
#把内容加进去
msg.attach(MIMEText(conntent,'plain','utf-8'))
 
#设置邮件主题
msg['Subject']="强化学习模型训练完毕"
 
#发送方信息
msg['From']=msg_from
 
#开始发送
 
#通过SSL方式发送，服务器地址和端口
s = smtplib.SMTP_SSL("smtp.qq.com", 465)
# 登录邮箱
s.login(msg_from, passwd)
#开始发送
s.sendmail(msg_from,to,msg.as_string())
print("强化学习模型训练完毕")

强化学习模型训练完毕
