In [1]:
# !pip install transformers accelerate
# from transformers import AutoTokenizer, AutoModel, EarlyStoppingCallback, AutoModelForSequenceClassification, AutoConfig,Trainer, TrainingArguments,DataCollatorWithPadding
import torch
import numpy as np
import pandas as pd
# !pip install datasets
from datasets import Dataset
# %pip install evaluate
import evaluate
from sklearn.model_selection import train_test_split
# from ipywidgets import FloatProgress
import csv
from optuna import Trial
from typing import Dict, Union, Any
import os
import sys

# notebook_login()

csv.field_size_limit(500 * 1024 * 1024)
CUDA_LAUNCH_BLOCKING=1
# get pwd
notebook_path = os.path.abspath('')

# Find the part of the path that contains 'commitFit'
commit_fit_path = None
for part in notebook_path.split(os.sep):
    print(part)
    if 'CommitFit' in part:
        commit_fit_path = notebook_path.split(part)[0] + part
        break

if commit_fit_path is None:
    raise ValueError("Path containing 'commitFit' not found in notebook path.")

# Add commitFit directory to Python path, so we can import moudule from commitfit folder directly
if commit_fit_path not in sys.path:
    sys.path.append(commit_fit_path)

from commitfit import CommitFitModel, CommitFitTrainer 
from commitfit import get_templated_dataset,sample_dataset


root
autodl-tmp
CommitFit


In [2]:
df = pd.read_csv(r'/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/dataset.csv', index_col=0, encoding='utf_8_sig')
# df.fillna('', inplace=True)
label2id={'C':0, 'A':1, 'P':2}
# df.reset_index(inplace=True)
df = df.rename(columns={'maintenance_type':'label','msgs':'text','commit_diff':'diffs'})
df = df.replace({"label": label2id})
# df = df['diffs']
# # print(df)

df
# test_sample = df.sample(n=3, random_state=1)

/tmp/ipykernel_2758/947145482.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({"label": label2id})


language                                    commit  \
0         C++  be937a3290223f926fe50684f1344569a573ed4b   
1         C++  c800d2e36954edddcb83aa1df7f623f2780c7780   
2         C++  469e56eeff17eb857c95e935ca7b49723c43470e   
3         C++  24f5d302c0906f3377f4d6bcc2735d943ce13e3d   
4         C++  1effdb7b959503596b07f7f3e74618ab63f9e5e5   
...       ...                                       ...   
1576     Java  e4bbfd537a63a52a6094491504fc7b0bb54bcb0e   
1577     Java  75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3   
1578     Java  6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce   
1579     Java  48701edad8513b27acec7216581e64637157c86a   
1580     Java  45529d30d41b8de338dfc2d26b61d1a79113c766   

                                             commit_url  label        user  \
0     https://github.com/tensorflow/tensorflow/commi...      0  tensorflow   
1     https://github.com/tensorflow/tensorflow/commi...      1  tensorflow   
2     https://github.com/tensorflow/tensorflow/commi...      2  tensorflow   
3     https://github.com/tensorflow/tensorflow/commi...      1  tensorflow   
4     https://github.com/tensorflow/tensorflow/commi...      2  tensorflow   
...                                                 ...    ...         ...   
1576                                                NaN      0    kiegroup   
1577                                                NaN      0    kiegroup   
1578                                                NaN      0    kiegroup   
1579                                                NaN      1    kiegroup   
1580                                                NaN      1    kiegroup   

            repo                                            feature  \
0     tensorflow  [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 6, ...   
1     tensorflow  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2     tensorflow  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3     tensorflow  [3, 37, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
4     tensorflow  [1, 0, 12, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
...          ...                                                ...   
1576      drools  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1577      drools  [2, 6, 2, 3, 0, 0, 0, 1, 7, 0, 0, 0, 0, 0, 0, ...   
1578      drools  [1, 1, 5, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1579      drools  [2, 24, 2, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1580      drools  [1, 10, 0, 0, 0, 0, 0, 1, 60, 0, 0, 1, 0, 0, 0...   

                                                  diffs  \
0     diff --git a/tensorflow/compiler/mlir/lite/fla...   
1     diff --git a/tensorflow/python/tools/saved_mod...   
2     diff --git a/.github/ISSUE_TEMPLATE/00-bug-iss...   
3     diff --git a/tensorflow/compiler/xla/pjrt/dist...   
4     diff --git a/tensorflow/core/common_runtime/ea...   
...                                                 ...   
1576  diff --git a/drools-persistence-jpa/src/main/j...   
1577  diff --git a/drools-compiler/src/main/java/org...   
1578  diff --git a/drools-core/src/main/java/org/dro...   
1579  diff --git a/drools-core/src/main/java/org/dro...   
1580  diff --git a/drools-compiler/src/test/java/org...   

                                                   text  
0     Fixing per axis quantization bug in flatbuffer...  
1     Add support for python expression as SavedMode...  
2     Fix GitHub issue templates. Actual fix for #36...  
3     Add new PjRT distributed APIs (KeyValueDelete,...  
4     Remove IsLocalDevice() since it's no longer us...  
...                                                 ...  
1576  fixing reflection constructor to use int inste...  
1577  Fix OutOfBoundException on- MemoryFileSystem.e...  
1578  [DROOLS-293] fix ObjectTypeNode id creation an...  
1579  DROOLS-515 Kie-Camel is broken after Camel Upd...  
1580  JBRULES-2934 Add NewRegisterWorkItemHandlerCom...  

[1581 rows x 9 columns]

In [3]:
train, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val_df, test = train_test_split(temp_df, test_size=0.5, random_state=42)

In [4]:
train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=20, random_state=42))

/tmp/ipykernel_2758/240346103.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=20, random_state=42))


In [5]:
train

language                                    commit  \
781       Python  a2479f46f3d05b37254ad701b6b76f84624d3cb5   
126          C++  6662fe7b185aab29aa4b2c5e08784e9da75bc700   
1323  TypeScript  177f1fc5dd489e90eb1c4cf055e342fbc4f6ef32   
683   JavaScript  ec7be48470e42472a07572b7f1ca2abc91bfdad3   
871       Python  daf4c358f7d382e7fc0466b06e3c528d24b3f760   
681   JavaScript  8f6f8820686cc57ab0ee3139c4d7d7c2c13b7014   
1402        Java  ca2f1678d75d9d42867f2124fa3e7dfcf1c367f7   
1072        Rust  33a4df8008ce138106a71b047ddef3ba57a0a28b   
552   JavaScript  0c7236b292a77e330710994417c4214475fb6880   
395           Go  7b48138ad0afc11d1ebbaa86095127e8384d6d42   
536   JavaScript  16aa2ce7fa42e7c46407b78966b7521d8e588a72   
1241  TypeScript  ea105a9290579040e1ab396c7c0d0d2d825aad3a   
1369        Java  7384d25cb3975a7fdc522ff8f84ab3dadcaba03a   
623   JavaScript  3beda63a7d749c86085147c800444f929a7a71ea   
1372        Java  64a2fde80a9f3aa71ac5c0e0b479c242bcecb561   
1186  TypeScript  1da5490ab8cd091a40338e845abe4a11552361a2   
1499        Java  f0f7133a3ae5cff39e4f13643c346fe3b234a8ac   
1470        Java  9d3a1f0f0f6f7c1781e7f6b5785e23db6eb5703a   
998         Rust  9db86f13f379e880ce3eba20285511dad3232d76   
93           C++  5422d863e175d92b9092a43dd6c9107843b1b943   
401           Go  ed09b4ea6a17566b546a9d3ae76876636710c6a0   
907         Rust  e67010b5e2eaa5a5ddb756d7ddc2dd0194f09a0a   
1385        Java  74066765bb8ca85864f75bde6091f96207f988cf   
448           Go  8d9e4345207013c55a8719995ec4ad4e9be466f2   
653   JavaScript  145c46ff3630e55b6c50ff479f54661ef54124bd   
463           Go  73890f31af5f1247c1f5b8131f136d1045d6b5f6   
1052        Rust  e6132809d27164077c2bca7f4cebdcea5e03eff0   
1442        Java  98a24828255cde13eaee893eafc9a049bb2183a7   
1502        Java  3e714ddd9f062e534c1ee028ac8b2269a062004b   
1370        Java  f64233fb2d9bcb77e9249d3bc497fd9d110e6a9f   
797       Python  1f16d4ce1c8929389c711fa18ae9c018fc79eefa   
1042        Rust  45b7057e07cf094627c2dc6313cf7664dbc69e99   
1047        Rust  31349a47d3fa12ed15f409654d0af2c0ba0645d2   
215          C++  4e1adcf4c7ed9db1c504658b857661b0ffb8bc0e   
889       Python  27f1c737f2cfc6e589c292776df6f78c08a4da91   
714       Python  d6eb66ed3c0dc1362c1fec46b2d9a60076812f50   
443           Go  ae768be874198b8fdf1a8a59ac09b5bbde524db2   
1352        Java  28696f9d6030a11da29b47c760026b7568002df8   
138          C++  c839b19b919f976f9c1fb695a883fadb6069bf3a   
1071        Rust  c20894583345d3a09c1142589132fa854bab1892   
1292  TypeScript  de7140853140029a3f48600b60e700464e7662b5   
1215  TypeScript  bf0b0a30e02d7a70e092f290680b941610d9cccc   
869       Python  b64e5919715f8dee546fbfc5049f8ec1574c2567   
1013        Rust  106bcb73bcfe1c3887795a6fa2b106c665df3d56   
372           Go  f73d059d80af7028531a12d76fb37fe4ea01254f   
132          C++  cabba0f15882317a5bf891b92e596b32761a13ca   
934         Rust  d8cb44036919a264c55f919609f208911a348de1   
120          C++  d37a9319ecd1723c7d50d63a87fb0d3b12a8f915   
1018        Rust  c48586de08c678b506f74d5a394baf3a8d15256a   
1172  TypeScript  7c02152e1ed348789f249d1755918721a7b22333   
329           Go  04623718ce75658d6d2e73ef2f0e99b99679e58d   
948         Rust  490fa25521eb5052f379c4877c2828b8e8582cc7   
833       Python  7500d0c61cfea3508bca9c53c144c0bc9c035142   
348           Go  98bbc54fdcd05a2f53c10e81be7cf94d1dc62522   
1250  TypeScript  17be8c5cd31c2ee036aadeeaf4cc19823c6f832a   
1089        Rust  fbd6ac71b55f681441647e4b0292d6c2f5c175fc   
827       Python  8eb73c8f17b52e2c40718b930fa03385fe27d981   
502   JavaScript  651280e5a22d08170187bea9a2b1697832c87ebc   
1451        Java  f55b7c350b928aa5419a1e3ee0fdbe4808731038   
805       Python  1a85699c03f902af23a9d2ddaae525fe4e077dbe   

                                             commit_url  label  \
781   https://github.com/django/django/commit/a2479f...      0   
126   https://github.com/ocornut/imgui/commit/6662fe...      0   
1323  https://github.com/ap

In [6]:
# train.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/20_train.csv',index=False)
# test.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/test.csv',index=False)
# val.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/eval.csv',index=False)
# train.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/20_train.csv',index=False)
# test.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/test.csv',index=False)
# val.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/eval.csv',index=False)

In [7]:
Dataset_train = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

In [8]:
train_dataset = get_templated_dataset(Dataset_train, candidate_labels=['Corrective','Adaptive','Perfective'], sample_size=8)

In [9]:
train_code_change = list(train['diffs'].astype(str))
test_code_change = list(test['diffs'].astype(str))

In [10]:
# list(train['message'].astype(str).values)
train_dataset

Dataset({
    features: ['language', 'commit', 'commit_url', 'label', 'user', 'repo', 'feature', 'diffs', 'text', '__index_level_0__'],
    num_rows: 84
})

In [11]:
len(train)

60

In [12]:
train['label'].value_counts()

label
0    20
1    20
2    20
Name: count, dtype: int64

In [13]:
test['label'].value_counts()

label
2    155
0     51
1     32
Name: count, dtype: int64

In [14]:
len(train_dataset)

84

In [15]:
from sklearn import  metrics

def compute_metrics(y_pred, y_test):
    # print(y_pred,y_test)
    # classification_report = metrics.classification_report(y_test,y_pred)
    accuracy_score = metrics.accuracy_score(y_test,y_pred)
    precision_score = metrics.precision_score(y_test,y_pred, average='macro')
    recall_score = metrics.recall_score(y_test,y_pred,average='macro')
    f1_score = metrics.f1_score(y_test,y_pred,average='macro')
    
    # 混淆矩阵
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:\n", cm)
    print(metrics.classification_report(y_test, y_pred, digits=4))
    # return {"classification_report": classification_report}
    return {"classification_report":metrics.classification_report(y_test, y_pred, digits=4),"Confusion Matrix":cm,"precision": round(precision_score, 4),"recall": round(recall_score, 4), "f1":round(f1_score, 4), "accuracy": round(accuracy_score, 4)}

In [16]:
train_dataset

Dataset({
    features: ['language', 'commit', 'commit_url', 'label', 'user', 'repo', 'feature', 'diffs', 'text', '__index_level_0__'],
    num_rows: 84
})

In [17]:
train

language                                    commit  \
781       Python  a2479f46f3d05b37254ad701b6b76f84624d3cb5   
126          C++  6662fe7b185aab29aa4b2c5e08784e9da75bc700   
1323  TypeScript  177f1fc5dd489e90eb1c4cf055e342fbc4f6ef32   
683   JavaScript  ec7be48470e42472a07572b7f1ca2abc91bfdad3   
871       Python  daf4c358f7d382e7fc0466b06e3c528d24b3f760   
681   JavaScript  8f6f8820686cc57ab0ee3139c4d7d7c2c13b7014   
1402        Java  ca2f1678d75d9d42867f2124fa3e7dfcf1c367f7   
1072        Rust  33a4df8008ce138106a71b047ddef3ba57a0a28b   
552   JavaScript  0c7236b292a77e330710994417c4214475fb6880   
395           Go  7b48138ad0afc11d1ebbaa86095127e8384d6d42   
536   JavaScript  16aa2ce7fa42e7c46407b78966b7521d8e588a72   
1241  TypeScript  ea105a9290579040e1ab396c7c0d0d2d825aad3a   
1369        Java  7384d25cb3975a7fdc522ff8f84ab3dadcaba03a   
623   JavaScript  3beda63a7d749c86085147c800444f929a7a71ea   
1372        Java  64a2fde80a9f3aa71ac5c0e0b479c242bcecb561   
1186  TypeScript  1da5490ab8cd091a40338e845abe4a11552361a2   
1499        Java  f0f7133a3ae5cff39e4f13643c346fe3b234a8ac   
1470        Java  9d3a1f0f0f6f7c1781e7f6b5785e23db6eb5703a   
998         Rust  9db86f13f379e880ce3eba20285511dad3232d76   
93           C++  5422d863e175d92b9092a43dd6c9107843b1b943   
401           Go  ed09b4ea6a17566b546a9d3ae76876636710c6a0   
907         Rust  e67010b5e2eaa5a5ddb756d7ddc2dd0194f09a0a   
1385        Java  74066765bb8ca85864f75bde6091f96207f988cf   
448           Go  8d9e4345207013c55a8719995ec4ad4e9be466f2   
653   JavaScript  145c46ff3630e55b6c50ff479f54661ef54124bd   
463           Go  73890f31af5f1247c1f5b8131f136d1045d6b5f6   
1052        Rust  e6132809d27164077c2bca7f4cebdcea5e03eff0   
1442        Java  98a24828255cde13eaee893eafc9a049bb2183a7   
1502        Java  3e714ddd9f062e534c1ee028ac8b2269a062004b   
1370        Java  f64233fb2d9bcb77e9249d3bc497fd9d110e6a9f   
797       Python  1f16d4ce1c8929389c711fa18ae9c018fc79eefa   
1042        Rust  45b7057e07cf094627c2dc6313cf7664dbc69e99   
1047        Rust  31349a47d3fa12ed15f409654d0af2c0ba0645d2   
215          C++  4e1adcf4c7ed9db1c504658b857661b0ffb8bc0e   
889       Python  27f1c737f2cfc6e589c292776df6f78c08a4da91   
714       Python  d6eb66ed3c0dc1362c1fec46b2d9a60076812f50   
443           Go  ae768be874198b8fdf1a8a59ac09b5bbde524db2   
1352        Java  28696f9d6030a11da29b47c760026b7568002df8   
138          C++  c839b19b919f976f9c1fb695a883fadb6069bf3a   
1071        Rust  c20894583345d3a09c1142589132fa854bab1892   
1292  TypeScript  de7140853140029a3f48600b60e700464e7662b5   
1215  TypeScript  bf0b0a30e02d7a70e092f290680b941610d9cccc   
869       Python  b64e5919715f8dee546fbfc5049f8ec1574c2567   
1013        Rust  106bcb73bcfe1c3887795a6fa2b106c665df3d56   
372           Go  f73d059d80af7028531a12d76fb37fe4ea01254f   
132          C++  cabba0f15882317a5bf891b92e596b32761a13ca   
934         Rust  d8cb44036919a264c55f919609f208911a348de1   
120          C++  d37a9319ecd1723c7d50d63a87fb0d3b12a8f915   
1018        Rust  c48586de08c678b506f74d5a394baf3a8d15256a   
1172  TypeScript  7c02152e1ed348789f249d1755918721a7b22333   
329           Go  04623718ce75658d6d2e73ef2f0e99b99679e58d   
948         Rust  490fa25521eb5052f379c4877c2828b8e8582cc7   
833       Python  7500d0c61cfea3508bca9c53c144c0bc9c035142   
348           Go  98bbc54fdcd05a2f53c10e81be7cf94d1dc62522   
1250  TypeScript  17be8c5cd31c2ee036aadeeaf4cc19823c6f832a   
1089        Rust  fbd6ac71b55f681441647e4b0292d6c2f5c175fc   
827       Python  8eb73c8f17b52e2c40718b930fa03385fe27d981   
502   JavaScript  651280e5a22d08170187bea9a2b1697832c87ebc   
1451        Java  f55b7c350b928aa5419a1e3ee0fdbe4808731038   
805       Python  1a85699c03f902af23a9d2ddaae525fe4e077dbe   

                                             commit_url  label  \
781   https://github.com/django/django/commit/a2479f...      0   
126   https://github.com/ocornut/imgui/commit/6662fe...      0   
1323  https://github.com/ap

In [18]:
model_id = "../../sentence-transformers/paraphrase-mpnet-base-v2"

In [19]:
def hp_space(trial: Trial) -> Dict[str, Union[float, int, str]]:
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-3, log=True),
        # "num_epochs": trial.suggest_int("num_epochs", 1, 3),
        # "batch_size": trial.suggest_categorical("batch_size", [8, 12, 16]),
        # "seed": trial.suggest_int("seed", 1, 40),
        # "num_iterations": trial.suggest_int("num_iterations", 10, 20),
        # "solver": trial.suggest_categorical("solver", ["newton-cg", "lbfgs", "liblinear"]),
    }
def model_init(params: Dict[str, Any]) -> CommitFitModel:
    params = params or {}
    # learning_rate = params.get("learning_rate")
    # num_iterations = params.get("num_iterations", 20)
    # solver = params.get("solver", "liblinear")
    # params = {
    #     "head_params": {
    #         # "max_iter": num_iterations,
    #         # "solver": solver,
    #     }
    # }
    return CommitFitModel.from_pretrained(model_id, **params)
def my_compute_objective(metrics):
    print('+++++++++++',metrics)
    return  metrics['accuracy']

In [20]:
trainer = CommitFitTrainer(
    train_dataset=train_dataset,
    train_code_change = train_code_change,
    test_code_change = test_code_change,
    eval_dataset=test_dataset,
    model_init=model_init,
    metric = compute_metrics,
    num_iterations=20,
    num_epochs=1
)
best_run = trainer.hyperparameter_search(direction="maximize", hp_space=hp_space, compute_objective=my_compute_objective, n_trials=5)

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
[I 2025-08-29 19:13:51,590] A new study created in memory with name: no-name-93ca4576-a2cb-46bf-9e30-292ee41e2da3
Trial: {'learning_rate': 1.6851708656253302e-06}
model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 3360
  Num epochs = 1
  Total optimization steps = 210
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/210 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 19:14:33,205] Trial 0 finished with value: 0.605 and parameters: {'learning_rate': 1.6851708656253302e-06}. Best is trial 0 with value: 0.605.
Trial: {'learning_rate': 3.058569187188438e-05}


Confusion Matrix:
 [[34  3 14]
 [ 3 23  6]
 [29 39 87]]
              precision    recall  f1-score   support

           0     0.5152    0.6667    0.5812        51
           1     0.3538    0.7188    0.4742        32
           2     0.8131    0.5613    0.6641       155

    accuracy                         0.6050       238
   macro avg     0.5607    0.6489    0.5732       238
weighted avg     0.6875    0.6050    0.6208       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5152    0.6667    0.5812        51\n           1     0.3538    0.7188    0.4742        32\n           2     0.8131    0.5613    0.6641       155\n\n    accuracy                         0.6050       238\n   macro avg     0.5607    0.6489    0.5732       238\nweighted avg     0.6875    0.6050    0.6208       238\n', 'Confusion Matrix': array([[34,  3, 14],
       [ 3, 23,  6],
       [29, 39, 87]]), 'precision': 0.5607, 'recall': 0.6489, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 3360
  Num epochs = 1
  Total optimization steps = 210
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/210 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 19:15:13,589] Trial 1 finished with value: 0.6849 and parameters: {'learning_rate': 3.058569187188438e-05}. Best is trial 1 with value: 0.6849.
Trial: {'learning_rate': 6.400976582840636e-06}


Confusion Matrix:
 [[ 36   0  15]
 [  1  24   7]
 [ 25  27 103]]
              precision    recall  f1-score   support

           0     0.5806    0.7059    0.6372        51
           1     0.4706    0.7500    0.5783        32
           2     0.8240    0.6645    0.7357       155

    accuracy                         0.6849       238
   macro avg     0.6251    0.7068    0.6504       238
weighted avg     0.7243    0.6849    0.6934       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5806    0.7059    0.6372        51\n           1     0.4706    0.7500    0.5783        32\n           2     0.8240    0.6645    0.7357       155\n\n    accuracy                         0.6849       238\n   macro avg     0.6251    0.7068    0.6504       238\nweighted avg     0.7243    0.6849    0.6934       238\n', 'Confusion Matrix': array([[ 36,   0,  15],
       [  1,  24,   7],
       [ 25,  27, 103]]), 'precision': 0.6251, 'recall'

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 3360
  Num epochs = 1
  Total optimization steps = 210
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/210 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 19:15:54,129] Trial 2 finished with value: 0.6597 and parameters: {'learning_rate': 6.400976582840636e-06}. Best is trial 1 with value: 0.6849.
Trial: {'learning_rate': 3.2421617802113626e-05}


Confusion Matrix:
 [[36  1 14]
 [ 1 24  7]
 [22 36 97]]
              precision    recall  f1-score   support

           0     0.6102    0.7059    0.6545        51
           1     0.3934    0.7500    0.5161        32
           2     0.8220    0.6258    0.7106       155

    accuracy                         0.6597       238
   macro avg     0.6085    0.6939    0.6271       238
weighted avg     0.7190    0.6597    0.6725       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.6102    0.7059    0.6545        51\n           1     0.3934    0.7500    0.5161        32\n           2     0.8220    0.6258    0.7106       155\n\n    accuracy                         0.6597       238\n   macro avg     0.6085    0.6939    0.6271       238\nweighted avg     0.7190    0.6597    0.6725       238\n', 'Confusion Matrix': array([[36,  1, 14],
       [ 1, 24,  7],
       [22, 36, 97]]), 'precision': 0.6085, 'recall': 0.6939, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 3360
  Num epochs = 1
  Total optimization steps = 210
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/210 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 19:16:34,601] Trial 3 finished with value: 0.6849 and parameters: {'learning_rate': 3.2421617802113626e-05}. Best is trial 1 with value: 0.6849.
Trial: {'learning_rate': 0.0005306188967027284}


Confusion Matrix:
 [[ 36   0  15]
 [  1  25   6]
 [ 24  29 102]]
              precision    recall  f1-score   support

           0     0.5902    0.7059    0.6429        51
           1     0.4630    0.7812    0.5814        32
           2     0.8293    0.6581    0.7338       155

    accuracy                         0.6849       238
   macro avg     0.6275    0.7151    0.6527       238
weighted avg     0.7288    0.6849    0.6938       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5902    0.7059    0.6429        51\n           1     0.4630    0.7812    0.5814        32\n           2     0.8293    0.6581    0.7338       155\n\n    accuracy                         0.6849       238\n   macro avg     0.6275    0.7151    0.6527       238\nweighted avg     0.7288    0.6849    0.6938       238\n', 'Confusion Matrix': array([[ 36,   0,  15],
       [  1,  25,   6],
       [ 24,  29, 102]]), 'precision': 0.6275, 'recall'

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 3360
  Num epochs = 1
  Total optimization steps = 210
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/210 [00:00<?, ?it/s]

***** Running evaluation *****
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix:
 [[ 51   0   0]
 [ 32   0   0]
 [155   0   0]]
              precision    recall  f1-score   support

           0     0.2143    1.0000    0.3529        51
           1     0.0000    0.0000    0.0000        32
           2     0.0000    0.0000    0.0000       155

    accuracy                         0.2143       238
   macro avg     0.0714    0.3333    0.1176       238
weighted avg     0.0459    0.2143    0.0756       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.2143    1.0000    0.3529        51\n           1     0.0000    0.0000    0.0000        32\n           2     0.0000    0.0000    0.0000       155\n\n    accuracy                         0.2143       238\n   macro avg     0.0714    0.3333    0.1176       238\nweighted avg     0.0459    0.2143    0.0756       238\n', 'Confusion Matrix': array([[ 51,   0,   0],
       [ 32,   0,   0],
       [155,   0,   0]]), 'precision': 0.0714, 'recall'

In [21]:
best_run

BestRun(run_id='1', objective=0.6849, hyperparameters={'learning_rate': 3.058569187188438e-05}, backend=<optuna.study.study.Study object at 0x7fafd70e1330>)

In [22]:
best_run.hyperparameters

{'learning_rate': 3.058569187188438e-05}

In [23]:
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 3360
  Num epochs = 1
  Total optimization steps = 210
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/210 [00:00<?, ?it/s]

In [24]:
fewshot_metrics = trainer.evaluate()
fewshot_metrics

***** Running evaluation *****


Confusion Matrix:
 [[40  2  9]
 [ 1 26  5]
 [28 30 97]]
              precision    recall  f1-score   support

           0     0.5797    0.7843    0.6667        51
           1     0.4483    0.8125    0.5778        32
           2     0.8739    0.6258    0.7293       155

    accuracy                         0.6849       238
   macro avg     0.6340    0.7409    0.6579       238
weighted avg     0.7536    0.6849    0.6955       238



{'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5797    0.7843    0.6667        51\n           1     0.4483    0.8125    0.5778        32\n           2     0.8739    0.6258    0.7293       155\n\n    accuracy                         0.6849       238\n   macro avg     0.6340    0.7409    0.6579       238\nweighted avg     0.7536    0.6849    0.6955       238\n',
 'Confusion Matrix': array([[40,  2,  9],
        [ 1, 26,  5],
        [28, 30, 97]]),
 'precision': 0.634,
 'recall': 0.7409,
 'f1': 0.6579,
 'accuracy': 0.6849}

In [25]:
#发送多种类型的邮件
from email.mime.multipart import MIMEMultipart
import smtplib

from email.mime.text import MIMEText
msg_from = '915803745@qq.com'  # 发送方邮箱
passwd = 'vcuosuurrgkfbdai'   #就是上面的授权码
 
# to= ['g.zhang@gotion.com', 'j.tong@gotion.com'] #接受方邮箱
to= ['j.tong@gotion.com'] #接受方邮箱
#设置邮件内容
#MIMEMultipart类可以放任何内容
msg = MIMEMultipart()
conntent=f"{fewshot_metrics}"
#把内容加进去
msg.attach(MIMEText(conntent,'plain','utf-8'))
 
#设置邮件主题
msg['Subject']="强化学习模型训练完毕"
 
#发送方信息
msg['From']=msg_from
 
#开始发送
 
#通过SSL方式发送，服务器地址和端口
s = smtplib.SMTP_SSL("smtp.qq.com", 465)
# 登录邮箱
s.login(msg_from, passwd)
#开始发送
s.sendmail(msg_from,to,msg.as_string())
print("强化学习模型训练完毕")

强化学习模型训练完毕
