In [1]:
# !pip install transformers accelerate
from transformers import EarlyStoppingCallback
import torch
import numpy as np
import pandas as pd
# !pip install datasets
from datasets import Dataset
# %pip install evaluate
import evaluate
from sklearn.model_selection import train_test_split
# from ipywidgets import FloatProgress
import csv
from optuna import Trial
from typing import Dict, Union, Any
import os
import sys

# notebook_login()

csv.field_size_limit(500 * 1024 * 1024)
CUDA_LAUNCH_BLOCKING=1
# get pwd
notebook_path = os.path.abspath('')

# Find the part of the path that contains 'commitFit'
commit_fit_path = None
for part in notebook_path.split(os.sep):
    print(part)
    if 'CommitFit' in part:
        commit_fit_path = notebook_path.split(part)[0] + part
        break

if commit_fit_path is None:
    raise ValueError("Path containing 'commitFit' not found in notebook path.")

# Add commitFit directory to Python path, so we can import moudule from commitfit folder directly
if commit_fit_path not in sys.path:
    sys.path.append(commit_fit_path)

from commitfit import CommitFitModel, CommitFitTrainer 
from commitfit import get_templated_dataset,sample_dataset


root
autodl-tmp
CommitFit


In [2]:
df = pd.read_csv(r'/root/autodl-tmp/CommitFit/dataset/Ghadhab/dataset.csv', index_col=0, encoding='utf_8_sig')
# df.fillna('', inplace=True)
label2id={'C':0, 'A':1, 'P':2}
df = df.rename(columns={'labels':'label','msgs':'text','commit_diff':'diffs'})
df = df.replace({"label": label2id})
# # print(df)
df
# test_sample = df.sample(n=3, random_state=1)

repo                                    commit  \
user                                                                     
ponsonio              RxJava  0531b8bff5c14d9504beefb4ad47f473e3a22932   
ponsonio              RxJava  0950c46beda335819928585f1262dfe1dca78a0b   
ponsonio              RxJava  0f92fdd8e6422d5b79c610a7fd8409d222315a49   
ponsonio              RxJava  100f571c9a2835d5a30a55374b9be74c147e031f   
ponsonio              RxJava  191f023cf5253ea90647bc091dcaf55ccdce81cc   
...                      ...                                       ...   
jenkinsci   clearcase-plugin  51e9da224f80254476a7dc446bca817b505381d8   
jexp            batch-import  609d6c4b1eea2c33d9fb950fcbb9ba9dc1f80fc3   
hdiv                    hdiv  19b650c78a1c76f4fd90274d7f163f863c0d39e4   
casidiablo       persistence  d7bf95159df37a3d338ca267dddd3d26b38ec37c   
jhy                    jsoup  d6fd1637307f6b088eb226c3f979085725530f32   

                 label                                               text  \
user                                                                        
ponsonio    Perfective              Change hasException to hasThrowable--   
ponsonio      Adaptive  Trying to extend the Scheduler interface accor...   
ponsonio      Adaptive   RunAsync method for outputting multiple values--   
ponsonio    Corrective  forEach with Action1 but not Observer--I re-re...   
ponsonio    Corrective  1.x: Fix Completable swallows- OnErrorNotImple...   
...                ...                                                ...   
jenkinsci   Perfective  Use a temporary file to decrease memory consum...   
jexp        Perfective  added a more memory efficient structure for st...   
hdiv        Perfective               Memory and performance optimizations   
casidiablo  Perfective  Now it is possible to specify the sqlite open ...   
jhy         Perfective            Performance improvment for Element.text   

                                                        diffs  \
user                                                            
ponsonio    diff --git a/rxjava-core/src/main/java/rx/Noti...   
ponsonio    diff --git a/rxjava-core/src/main/java/rx/Sche...   
ponsonio    diff --git a/rxjava-contrib/rxjava-async-util/...   
ponsonio    diff --git a/language-adaptors/rxjava-groovy/s...   
ponsonio    diff --git a/src/main/java/rx/Completable.java...   
...                                                       ...   
jenkinsci   diff --git a/src/main/java/hudson/plugins/clea...   
jexp        diff --git a/src/main/java/org/neo4j/batchimpo...   
hdiv        diff --git a/hdiv-config/src/main/java/org/hdi...   
casidiablo  diff --git a/pom.xml b/pom.xml\nindex 394263b....   
jhy         diff --git a/src/main/java/org/jsoup/helper/St...   

                                                      feature  
user                                                           
ponsonio    [1, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
ponsonio    [2, 44, 0, 0, 30, 0, 0, 1, 18, 0, 0, 0, 0, 0, ...  
ponsonio    [2, 53, 0, 0, 42, 0, 0, 1, 45, 1, 0, 0, 0, 0, ...  
ponsonio    [1, 5, 122, 9, 10, 9, 4, 1, 5, 18, 2, 0, 0, 0,...  
ponsonio    [1, 1, 0, 0, 0, 0, 0, 1, 21, 0, 0, 0, 0, 0, 0,...  
...                                                       ...  
jenkinsci   [2, 12, 0, 4, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,...  
jexp        [10, 159, 29, 35, 9, 2, 1, 5, 106, 0, 4, 8, 0,...  
hdiv        [31, 302, 131, 140, 170, 89, 53, 7, 88, 14, 17...  
casidiablo  [5, 57, 20, 9, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
jhy         [3, 11, 11, 9, 13, 0, 0, 1, 0, 8, 0, 0, 1, 0, ...  

[1781 rows x 6 columns]

In [3]:
train, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val, test = train_test_split(temp_df, test_size=0.5, random_state=42)

In [4]:
train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=10, random_state=42))

/tmp/ipykernel_2120/1938515031.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=10, random_state=42))


In [5]:
# train.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/10_train.csv')
# test.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/test.csv')
# val.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/val.csv')

# train.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/10_train.csv')
# test.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/test.csv')
# val.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/val.csv')

In [6]:
Dataset_train = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

In [7]:
train_dataset = get_templated_dataset(Dataset_train, candidate_labels=['Corrective','Adaptive','Perfective'], sample_size=8)

In [8]:
train_code_change = list(train['diffs'].astype(str))
test_code_change = list(test['diffs'].astype(str))

In [9]:
# list(train['message'].astype(str).values)
train_dataset

Dataset({
    features: ['repo', 'commit', 'label', 'text', 'diffs', 'feature', 'user'],
    num_rows: 54
})

In [10]:
len(train)

30

In [11]:
train['label'].value_counts()

label
Adaptive      10
Corrective    10
Perfective    10
Name: count, dtype: int64

In [12]:
test['label'].value_counts()

label
Perfective    100
Corrective     89
Adaptive       79
Name: count, dtype: int64

In [13]:
len(train_dataset)

54

In [14]:
from sklearn import  metrics

def compute_metrics(y_pred, y_test):
    # print(y_pred,y_test)
    # classification_report = metrics.classification_report(y_test,y_pred)
    accuracy_score = metrics.accuracy_score(y_test,y_pred)
    precision_score = metrics.precision_score(y_test,y_pred, average='macro')
    recall_score = metrics.recall_score(y_test,y_pred,average='macro')
    f1_score = metrics.f1_score(y_test,y_pred,average='macro')
    
    # 混淆矩阵
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:\n", cm)
    print(metrics.classification_report(y_test, y_pred, digits=4))
    # return {"classification_report": classification_report}
    return {"classification_report":metrics.classification_report(y_test, y_pred, digits=4),"Confusion Matrix":cm,"precision": round(precision_score, 4),"recall": round(recall_score, 4), "f1":round(f1_score, 4), "accuracy": round(accuracy_score, 4)}

In [15]:
model_id = "../../sentence-transformers/paraphrase-mpnet-base-v2"

In [16]:
def hp_space(trial: Trial) -> Dict[str, Union[float, int, str]]:
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-3, log=True),
        # "num_epochs": trial.suggest_int("num_epochs", 1, 3),
        # "batch_size": trial.suggest_categorical("batch_size", [8, 12, 16]),
        # "seed": trial.suggest_int("seed", 1, 40),
        # "num_iterations": trial.suggest_int("num_iterations", 10, 20),
        # "solver": trial.suggest_categorical("solver", ["newton-cg", "lbfgs", "liblinear"]),
    }
def model_init(params: Dict[str, Any]) -> CommitFitModel:
    params = params or {}
    # learning_rate = params.get("learning_rate")
    # num_iterations = params.get("num_iterations", 20)
    # solver = params.get("solver", "liblinear")
    # params = {
    #     "head_params": {
    #         # "max_iter": num_iterations,
    #         # "solver": solver,
    #     }
    # }
    return CommitFitModel.from_pretrained(model_id, **params)
def my_compute_objective(metrics):
    print('+++++++++++',metrics)
    return  metrics['accuracy']

In [17]:
trainer = CommitFitTrainer(
    train_dataset=train_dataset,
    train_code_change = train_code_change,
    test_code_change = test_code_change,
    eval_dataset=test_dataset,
    model_init=model_init,
    metric = compute_metrics,
    num_iterations=20,
    num_epochs=1
)
best_run = trainer.hyperparameter_search(direction="maximize", hp_space=hp_space, compute_objective=my_compute_objective, n_trials=10)

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
[I 2025-08-29 08:43:08,746] A new study created in memory with name: no-name-f67d5230-ecbc-47f4-886b-d460cea71a97
Trial: {'learning_rate': 0.0002608323988034819}
model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix:
 [[  0  79   0]
 [  0  89   0]
 [  0 100   0]]
              precision    recall  f1-score   support

    Adaptive     0.0000    0.0000    0.0000        79
  Corrective     0.3321    1.0000    0.4986        89
  Perfective     0.0000    0.0000    0.0000       100

    accuracy                         0.3321       268
   macro avg     0.1107    0.3333    0.1662       268
weighted avg     0.1103    0.3321    0.1656       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.0000    0.0000    0.0000        79\n  Corrective     0.3321    1.0000    0.4986        89\n  Perfective     0.0000    0.0000    0.0000       100\n\n    accuracy                         0.3321       268\n   macro avg     0.1107    0.3333    0.1662       268\nweighted avg     0.1103    0.3321    0.1656       268\n', 'Confusion Matrix': array([[  0,  79,   0],
       [  0,  89,   0],
       [  0, 100,   0]]), 'precision': 0.1107, 'recall'

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:43:54,280] Trial 1 finished with value: 0.6604 and parameters: {'learning_rate': 3.759229662217752e-06}. Best is trial 1 with value: 0.6604.
Trial: {'learning_rate': 2.4849188429207952e-05}


Confusion Matrix:
 [[55 12 12]
 [13 72  4]
 [38 12 50]]
              precision    recall  f1-score   support

    Adaptive     0.5189    0.6962    0.5946        79
  Corrective     0.7500    0.8090    0.7784        89
  Perfective     0.7576    0.5000    0.6024       100

    accuracy                         0.6604       268
   macro avg     0.6755    0.6684    0.6585       268
weighted avg     0.6847    0.6604    0.6585       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5189    0.6962    0.5946        79\n  Corrective     0.7500    0.8090    0.7784        89\n  Perfective     0.7576    0.5000    0.6024       100\n\n    accuracy                         0.6604       268\n   macro avg     0.6755    0.6684    0.6585       268\nweighted avg     0.6847    0.6604    0.6585       268\n', 'Confusion Matrix': array([[55, 12, 12],
       [13, 72,  4],
       [38, 12, 50]]), 'precision': 0.6755, 'recall': 0.6684, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:44:16,505] Trial 2 finished with value: 0.6604 and parameters: {'learning_rate': 2.4849188429207952e-05}. Best is trial 1 with value: 0.6604.
Trial: {'learning_rate': 1.949533900454113e-06}


Confusion Matrix:
 [[62  6 11]
 [25 63  1]
 [43  5 52]]
              precision    recall  f1-score   support

    Adaptive     0.4769    0.7848    0.5933        79
  Corrective     0.8514    0.7079    0.7730        89
  Perfective     0.8125    0.5200    0.6341       100

    accuracy                         0.6604       268
   macro avg     0.7136    0.6709    0.6668       268
weighted avg     0.7265    0.6604    0.6682       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4769    0.7848    0.5933        79\n  Corrective     0.8514    0.7079    0.7730        89\n  Perfective     0.8125    0.5200    0.6341       100\n\n    accuracy                         0.6604       268\n   macro avg     0.7136    0.6709    0.6668       268\nweighted avg     0.7265    0.6604    0.6682       268\n', 'Confusion Matrix': array([[62,  6, 11],
       [25, 63,  1],
       [43,  5, 52]]), 'precision': 0.7136, 'recall': 0.6709, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:44:38,649] Trial 3 finished with value: 0.6642 and parameters: {'learning_rate': 1.949533900454113e-06}. Best is trial 3 with value: 0.6642.
Trial: {'learning_rate': 8.617797512442047e-06}


Confusion Matrix:
 [[47 17 15]
 [14 70  5]
 [27 12 61]]
              precision    recall  f1-score   support

    Adaptive     0.5341    0.5949    0.5629        79
  Corrective     0.7071    0.7865    0.7447        89
  Perfective     0.7531    0.6100    0.6740       100

    accuracy                         0.6642       268
   macro avg     0.6647    0.6638    0.6605       268
weighted avg     0.6733    0.6642    0.6647       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5341    0.5949    0.5629        79\n  Corrective     0.7071    0.7865    0.7447        89\n  Perfective     0.7531    0.6100    0.6740       100\n\n    accuracy                         0.6642       268\n   macro avg     0.6647    0.6638    0.6605       268\nweighted avg     0.6733    0.6642    0.6647       268\n', 'Confusion Matrix': array([[47, 17, 15],
       [14, 70,  5],
       [27, 12, 61]]), 'precision': 0.6647, 'recall': 0.6638, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:45:00,377] Trial 4 finished with value: 0.6716 and parameters: {'learning_rate': 8.617797512442047e-06}. Best is trial 4 with value: 0.6716.
Trial: {'learning_rate': 1.59357778936383e-06}


Confusion Matrix:
 [[64  8  7]
 [18 71  0]
 [46  9 45]]
              precision    recall  f1-score   support

    Adaptive     0.5000    0.8101    0.6184        79
  Corrective     0.8068    0.7978    0.8023        89
  Perfective     0.8654    0.4500    0.5921       100

    accuracy                         0.6716       268
   macro avg     0.7241    0.6860    0.6709       268
weighted avg     0.7382    0.6716    0.6696       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5000    0.8101    0.6184        79\n  Corrective     0.8068    0.7978    0.8023        89\n  Perfective     0.8654    0.4500    0.5921       100\n\n    accuracy                         0.6716       268\n   macro avg     0.7241    0.6860    0.6709       268\nweighted avg     0.7382    0.6716    0.6696       268\n', 'Confusion Matrix': array([[64,  8,  7],
       [18, 71,  0],
       [46,  9, 45]]), 'precision': 0.7241, 'recall': 0.686, 'f1': 0.6

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:45:20,513] Trial 5 finished with value: 0.653 and parameters: {'learning_rate': 1.59357778936383e-06}. Best is trial 4 with value: 0.6716.
Trial: {'learning_rate': 2.339858260860644e-05}


Confusion Matrix:
 [[47 18 14]
 [15 68  6]
 [27 13 60]]
              precision    recall  f1-score   support

    Adaptive     0.5281    0.5949    0.5595        79
  Corrective     0.6869    0.7640    0.7234        89
  Perfective     0.7500    0.6000    0.6667       100

    accuracy                         0.6530       268
   macro avg     0.6550    0.6530    0.6499       268
weighted avg     0.6636    0.6530    0.6539       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.5281    0.5949    0.5595        79\n  Corrective     0.6869    0.7640    0.7234        89\n  Perfective     0.7500    0.6000    0.6667       100\n\n    accuracy                         0.6530       268\n   macro avg     0.6550    0.6530    0.6499       268\nweighted avg     0.6636    0.6530    0.6539       268\n', 'Confusion Matrix': array([[47, 18, 14],
       [15, 68,  6],
       [27, 13, 60]]), 'precision': 0.655, 'recall': 0.653, 'f1': 0.64

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:45:40,892] Trial 6 finished with value: 0.653 and parameters: {'learning_rate': 2.339858260860644e-05}. Best is trial 4 with value: 0.6716.
Trial: {'learning_rate': 1.4233552274281953e-05}


Confusion Matrix:
 [[61  7 11]
 [27 58  4]
 [41  3 56]]
              precision    recall  f1-score   support

    Adaptive     0.4729    0.7722    0.5865        79
  Corrective     0.8529    0.6517    0.7389        89
  Perfective     0.7887    0.5600    0.6550       100

    accuracy                         0.6530       268
   macro avg     0.7048    0.6613    0.6601       268
weighted avg     0.7169    0.6530    0.6627       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4729    0.7722    0.5865        79\n  Corrective     0.8529    0.6517    0.7389        89\n  Perfective     0.7887    0.5600    0.6550       100\n\n    accuracy                         0.6530       268\n   macro avg     0.7048    0.6613    0.6601       268\nweighted avg     0.7169    0.6530    0.6627       268\n', 'Confusion Matrix': array([[61,  7, 11],
       [27, 58,  4],
       [41,  3, 56]]), 'precision': 0.7048, 'recall': 0.6613, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:46:03,498] Trial 7 finished with value: 0.653 and parameters: {'learning_rate': 1.4233552274281953e-05}. Best is trial 4 with value: 0.6716.
Trial: {'learning_rate': 1.834447076449719e-05}


Confusion Matrix:
 [[61  5 13]
 [26 59  4]
 [41  4 55]]
              precision    recall  f1-score   support

    Adaptive     0.4766    0.7722    0.5894        79
  Corrective     0.8676    0.6629    0.7516        89
  Perfective     0.7639    0.5500    0.6395       100

    accuracy                         0.6530       268
   macro avg     0.7027    0.6617    0.6602       268
weighted avg     0.7136    0.6530    0.6620       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4766    0.7722    0.5894        79\n  Corrective     0.8676    0.6629    0.7516        89\n  Perfective     0.7639    0.5500    0.6395       100\n\n    accuracy                         0.6530       268\n   macro avg     0.7027    0.6617    0.6602       268\nweighted avg     0.7136    0.6530    0.6620       268\n', 'Confusion Matrix': array([[61,  5, 13],
       [26, 59,  4],
       [41,  4, 55]]), 'precision': 0.7027, 'recall': 0.6617, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-08-29 08:46:25,849] Trial 8 finished with value: 0.6493 and parameters: {'learning_rate': 1.834447076449719e-05}. Best is trial 4 with value: 0.6716.
Trial: {'learning_rate': 0.0007413477135620367}


Confusion Matrix:
 [[56  6 17]
 [25 59  5]
 [37  4 59]]
              precision    recall  f1-score   support

    Adaptive     0.4746    0.7089    0.5685        79
  Corrective     0.8551    0.6629    0.7468        89
  Perfective     0.7284    0.5900    0.6519       100

    accuracy                         0.6493       268
   macro avg     0.6860    0.6539    0.6558       268
weighted avg     0.6956    0.6493    0.6589       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4746    0.7089    0.5685        79\n  Corrective     0.8551    0.6629    0.7468        89\n  Perfective     0.7284    0.5900    0.6519       100\n\n    accuracy                         0.6493       268\n   macro avg     0.6860    0.6539    0.6558       268\nweighted avg     0.6956    0.6493    0.6589       268\n', 'Confusion Matrix': array([[56,  6, 17],
       [25, 59,  5],
       [37,  4, 59]]), 'precision': 0.686, 'recall': 0.6539, 'f1': 0.6

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

***** Running evaluation *****
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/root/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix:
 [[  0  79   0]
 [  0  89   0]
 [  0 100   0]]
              precision    recall  f1-score   support

    Adaptive     0.0000    0.0000    0.0000        79
  Corrective     0.3321    1.0000    0.4986        89
  Perfective     0.0000    0.0000    0.0000       100

    accuracy                         0.3321       268
   macro avg     0.1107    0.3333    0.1662       268
weighted avg     0.1103    0.3321    0.1656       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.0000    0.0000    0.0000        79\n  Corrective     0.3321    1.0000    0.4986        89\n  Perfective     0.0000    0.0000    0.0000       100\n\n    accuracy                         0.3321       268\n   macro avg     0.1107    0.3333    0.1662       268\nweighted avg     0.1103    0.3321    0.1656       268\n', 'Confusion Matrix': array([[  0,  79,   0],
       [  0,  89,   0],
       [  0, 100,   0]]), 'precision': 0.1107, 'recall'

In [18]:
# best_run

In [19]:
best_run.hyperparameters

{'learning_rate': 8.617797512442047e-06}

In [20]:
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 1
  Total optimization steps = 135
  Total train batch size = 16


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/135 [00:00<?, ?it/s]

In [21]:
fewshot_metrics = trainer.evaluate()
fewshot_metrics

***** Running evaluation *****


Confusion Matrix:
 [[56 15  8]
 [16 72  1]
 [42 12 46]]
              precision    recall  f1-score   support

    Adaptive     0.4912    0.7089    0.5803        79
  Corrective     0.7273    0.8090    0.7660        89
  Perfective     0.8364    0.4600    0.5935       100

    accuracy                         0.6493       268
   macro avg     0.6850    0.6593    0.6466       268
weighted avg     0.6984    0.6493    0.6469       268



{'classification_report': '              precision    recall  f1-score   support\n\n    Adaptive     0.4912    0.7089    0.5803        79\n  Corrective     0.7273    0.8090    0.7660        89\n  Perfective     0.8364    0.4600    0.5935       100\n\n    accuracy                         0.6493       268\n   macro avg     0.6850    0.6593    0.6466       268\nweighted avg     0.6984    0.6493    0.6469       268\n',
 'Confusion Matrix': array([[56, 15,  8],
        [16, 72,  1],
        [42, 12, 46]]),
 'precision': 0.685,
 'recall': 0.6593,
 'f1': 0.6466,
 'accuracy': 0.6493}

In [22]:
#发送多种类型的邮件
from email.mime.multipart import MIMEMultipart
import smtplib

from email.mime.text import MIMEText
msg_from = '915803745@qq.com'  # 发送方邮箱
passwd = 'vcuosuurrgkfbdai'   #就是上面的授权码
 
# to= ['g.zhang@gotion.com', 'j.tong@gotion.com'] #接受方邮箱
to= ['j.tong@gotion.com'] #接受方邮箱
#设置邮件内容
#MIMEMultipart类可以放任何内容
msg = MIMEMultipart()
conntent=f"{fewshot_metrics}"
#把内容加进去
msg.attach(MIMEText(conntent,'plain','utf-8'))
 
#设置邮件主题
msg['Subject']="强化学习模型训练完毕"
 
#发送方信息
msg['From']=msg_from
 
#开始发送
 
#通过SSL方式发送，服务器地址和端口
s = smtplib.SMTP_SSL("smtp.qq.com", 465)
# 登录邮箱
s.login(msg_from, passwd)
#开始发送
s.sendmail(msg_from,to,msg.as_string())
print("强化学习模型训练完毕")

强化学习模型训练完毕
