In [1]:
# !pip install transformers accelerate
# from transformers import AutoTokenizer, AutoModel, EarlyStoppingCallback, AutoModelForSequenceClassification, AutoConfig,Trainer, TrainingArguments,DataCollatorWithPadding
import torch
import numpy as np
import pandas as pd
# !pip install datasets
from datasets import Dataset
# %pip install evaluate
import evaluate
from sklearn.model_selection import train_test_split
# from ipywidgets import FloatProgress
import csv
from optuna import Trial
from typing import Dict, Union, Any
import os
import sys

# notebook_login()

csv.field_size_limit(500 * 1024 * 1024)
CUDA_LAUNCH_BLOCKING=1
# get pwd
notebook_path = os.path.abspath('')

# Find the part of the path that contains 'commitFit'
commit_fit_path = None
for part in notebook_path.split(os.sep):
    print(part)
    if 'CommitFit' in part:
        commit_fit_path = notebook_path.split(part)[0] + part
        break

if commit_fit_path is None:
    raise ValueError("Path containing 'commitFit' not found in notebook path.")

# Add commitFit directory to Python path, so we can import moudule from commitfit folder directly
if commit_fit_path not in sys.path:
    sys.path.append(commit_fit_path)

from commitfit import CommitFitModel, CommitFitTrainer 
from commitfit import get_templated_dataset,sample_dataset


root
autodl-tmp
CommitFit


In [2]:
df = pd.read_csv(r'/root/autodl-tmp/CommitFit/dataset/multi-lang-annotated/dataset.csv', index_col=0, encoding='utf_8_sig')
# df.fillna('', inplace=True)
label2id={'C':0, 'A':1, 'P':2}
# df.reset_index(inplace=True)
df = df.rename(columns={'maintenance_type':'label','commit_message':'text','commit_diff':'diffs'})
df = df.replace({"label": label2id})
# df = df['diffs']
# # print(df)

df
# test_sample = df.sample(n=3, random_state=1)

/tmp/ipykernel_1492/3292594428.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({"label": label2id})


label  \
commit_sha                                        
be937a3290223f926fe50684f1344569a573ed4b      0   
c800d2e36954edddcb83aa1df7f623f2780c7780      1   
469e56eeff17eb857c95e935ca7b49723c43470e      2   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d      1   
1effdb7b959503596b07f7f3e74618ab63f9e5e5      2   
...                                         ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e      0   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3      0   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce      0   
48701edad8513b27acec7216581e64637157c86a      1   
45529d30d41b8de338dfc2d26b61d1a79113c766      1   

                                                                                      diffs  \
commit_sha                                                                                    
be937a3290223f926fe50684f1344569a573ed4b  diff --git a/tensorflow/compiler/mlir/lite/fla...   
c800d2e36954edddcb83aa1df7f623f2780c7780  diff --git a/tensorflow/python/tools/saved_mod...   
469e56eeff17eb857c95e935ca7b49723c43470e  diff --git a/.github/ISSUE_TEMPLATE/00-bug-iss...   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d  diff --git a/tensorflow/compiler/xla/pjrt/dist...   
1effdb7b959503596b07f7f3e74618ab63f9e5e5  diff --git a/tensorflow/core/common_runtime/ea...   
...                                                                                     ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e  diff --git a/drools-persistence-jpa/src/main/j...   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3  diff --git a/drools-compiler/src/main/java/org...   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce  diff --git a/drools-core/src/main/java/org/dro...   
48701edad8513b27acec7216581e64637157c86a  diff --git a/drools-core/src/main/java/org/dro...   
45529d30d41b8de338dfc2d26b61d1a79113c766  diff --git a/drools-compiler/src/test/java/org...   

                                                                                       text  \
commit_sha                                                                                    
be937a3290223f926fe50684f1344569a573ed4b  Fixing per axis quantization bug in flatbuffer...   
c800d2e36954edddcb83aa1df7f623f2780c7780  Add support for python expression as SavedMode...   
469e56eeff17eb857c95e935ca7b49723c43470e  Fix GitHub issue templates. Actual fix for #36...   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d  Add new PjRT distributed APIs (KeyValueDelete,...   
1effdb7b959503596b07f7f3e74618ab63f9e5e5  Remove IsLocalDevice() since it's no longer us...   
...                                                                                     ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e  fixing reflection constructor to use int inste...   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3  Fix OutOfBoundException on- MemoryFileSystem.e...   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce  [DROOLS-293] fix ObjectTypeNode id creation an...   
48701edad8513b27acec7216581e64637157c86a  DROOLS-515 Kie-Camel is broken after Camel Upd...   
45529d30d41b8de338dfc2d26b61d1a79113c766  JBRULES-2934 Add NewRegisterWorkItemHandlerCom...   

                                          CODE_CHANGE_FILE  \
commit_sha                                                   
be937a3290223f926fe50684f1344569a573ed4b                 1   
c800d2e36954edddcb83aa1df7f623f2780c7780                 0   
469e56eeff17eb857c95e935ca7b49723c43470e                 0   
24f5d302c0906f3377f4d6bcc2735d943ce13e3d                 3   
1effdb7b959503596b07f7f3e74618ab63f9e5e5                 1   
...                                                    ...   
e4bbfd537a63a52a6094491504fc7b0bb54bcb0e                 1   
75b81dcbd26a11d5b370ea5bdf102c2d62ebd0c3                 2   
6bc9677bbe919cd5bcadd8af2f5b0c838757a4ce                 1   
48701edad8513b27acec7216581e64637157c86a                 2   
45529d30d41b8de338dfc2d26b61d1a79113c766                 1   

                                          CODE_ADD_CODE_LINE  \
commit_sha                         

In [3]:
train, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val_df, test = train_test_split(temp_df, test_size=0.5, random_state=42)

In [4]:
train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=10, random_state=42))

/tmp/ipykernel_1492/1938515031.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train = train.groupby("label", group_keys=False).apply(lambda x: x.sample(n=10, random_state=42))


In [5]:
train

label  \
commit_sha                                        
a2479f46f3d05b37254ad701b6b76f84624d3cb5      0   
6662fe7b185aab29aa4b2c5e08784e9da75bc700      0   
177f1fc5dd489e90eb1c4cf055e342fbc4f6ef32      0   
ec7be48470e42472a07572b7f1ca2abc91bfdad3      0   
daf4c358f7d382e7fc0466b06e3c528d24b3f760      0   
8f6f8820686cc57ab0ee3139c4d7d7c2c13b7014      0   
ca2f1678d75d9d42867f2124fa3e7dfcf1c367f7      0   
33a4df8008ce138106a71b047ddef3ba57a0a28b      0   
0c7236b292a77e330710994417c4214475fb6880      0   
7b48138ad0afc11d1ebbaa86095127e8384d6d42      0   
ed09b4ea6a17566b546a9d3ae76876636710c6a0      1   
e67010b5e2eaa5a5ddb756d7ddc2dd0194f09a0a      1   
74066765bb8ca85864f75bde6091f96207f988cf      1   
8d9e4345207013c55a8719995ec4ad4e9be466f2      1   
145c46ff3630e55b6c50ff479f54661ef54124bd      1   
73890f31af5f1247c1f5b8131f136d1045d6b5f6      1   
e6132809d27164077c2bca7f4cebdcea5e03eff0      1   
98a24828255cde13eaee893eafc9a049bb2183a7      1   
3e714ddd9f062e534c1ee028ac8b2269a062004b      1   
f64233fb2d9bcb77e9249d3bc497fd9d110e6a9f      1   
de7140853140029a3f48600b60e700464e7662b5      2   
bf0b0a30e02d7a70e092f290680b941610d9cccc      2   
b64e5919715f8dee546fbfc5049f8ec1574c2567      2   
106bcb73bcfe1c3887795a6fa2b106c665df3d56      2   
f73d059d80af7028531a12d76fb37fe4ea01254f      2   
cabba0f15882317a5bf891b92e596b32761a13ca      2   
d8cb44036919a264c55f919609f208911a348de1      2   
d37a9319ecd1723c7d50d63a87fb0d3b12a8f915      2   
c48586de08c678b506f74d5a394baf3a8d15256a      2   
7c02152e1ed348789f249d1755918721a7b22333      2   

                                                                                      diffs  \
commit_sha                                                                                    
a2479f46f3d05b37254ad701b6b76f84624d3cb5  diff --git a/django/contrib/auth/migrations/00...   
6662fe7b185aab29aa4b2c5e08784e9da75bc700  diff --git a/stb_truetype.h b/stb_truetype.h\n...   
177f1fc5dd489e90eb1c4cf055e342fbc4f6ef32  diff --git a/src/component/toolbox/feature/Sav...   
ec7be48470e42472a07572b7f1ca2abc91bfdad3  diff --git a/src/controllers/controller.scatte...   
daf4c358f7d382e7fc0466b06e3c528d24b3f760  diff --git a/library/packaging/pip b/library/p...   
8f6f8820686cc57ab0ee3139c4d7d7c2c13b7014  diff --git a/src/elements/element.point.js b/s...   
ca2f1678d75d9d42867f2124fa3e7dfcf1c367f7  diff --git a/CHANGES.txt b/CHANGES.txt\nindex ...   
33a4df8008ce138106a71b047ddef3ba57a0a28b  diff --git a/crates/bevy_text/src/lib.rs b/cra...   
0c7236b292a77e330710994417c4214475fb6880  diff --git a/lib/axios.js b/lib/axios.js\ninde...   
7b48138ad0afc11d1ebbaa86095127e8384d6d42  diff --git a/adapters/outbound/base.go b/adapt...   
ed09b4ea6a17566b546a9d3ae76876636710c6a0  diff --git a/common/net/json/host.go b/common/...   
e67010b5e2eaa5a5ddb756d7ddc2dd0194f09a0a  diff --git a/cli/file_fetcher.rs b/cli/file_fe...   
74066765bb8ca85864f75bde6091f96207f988cf  diff --git a/src/main/java/org/apache/hadoop/h...   
8d9e4345207013c55a8719995ec4ad4e9be466f2  diff --git a/truststore_nss.go b/truststore_ns...   
145c46ff3630e55b6c50ff479f54661ef54124bd  diff --git a/lib/dependencies/DelegatedExports...   
73890f31af5f1247c1f5b8131f136d1045d6b5f6  diff --git a/.goreleaser.yml b/.goreleaser.yml...   
e6132809d27164077c2bca7f4cebdcea5e03eff0  diff --git a/src/api/core/organizations.rs b/s...   
98a24828255cde13eaee893eafc9a049bb2183a7  diff --git a/src/test/java/org/elasticsearch/t...   
3e714ddd9f062e534c1ee028ac8b2269a062004b  diff --git a/platform-resources/src/META-INF/X...   
f64233fb2d9bcb77e9249d3bc497fd9d110e6a9f  diff --git a/src/main/java/rx/Single.java b/sr...   
de7140853140029a3f48600b60e700464e7662b5  diff --git a/packages/plugin-legacy/index.js b...   
bf0b0a30e02d7a70e092f290680b941610d9cccc  diff --git a/api/openapi.yml b/api/openapi.yml...   
b64e5919715f8dee546fbfc5049f8ec1574c2567  diff --git a/keras/layers/recurrent.py b/keras...   
106bcb73bcfe1c3887795a6fa2b106c665

In [6]:
# train.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/10_train.csv',index=False)
# test.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/test.csv',index=False)
# val.to_csv('/root/autodl-tmp/COLARE-main/dataset/multi-lang-exp/eval.csv',index=False)
# train.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/10_train.csv',index=False)
# test.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/test.csv',index=False)
# val.to_csv('/root/autodl-tmp/CommitFit/dataset/multi-lang-exp/eval.csv',index=False)

In [7]:
Dataset_train = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

In [8]:
train_dataset = get_templated_dataset(Dataset_train, candidate_labels=['Corrective','Adaptive','Perfective'], sample_size=8)

In [9]:
train_code_change = list(train['diffs'].astype(str))
test_code_change = list(test['diffs'].astype(str))

In [10]:
# list(train['message'].astype(str).values)
train_dataset

Dataset({
    features: ['label', 'diffs', 'text', 'CODE_CHANGE_FILE', 'CODE_ADD_CODE_LINE', 'CODE_DEL_CODE_LINE', 'CODE_MOD_CODE_LINE', 'CODE_ADD_COMMENT_LINE', 'CODE_DEL_COMMENT_LINE', 'CODE_MOD_COMMENT_LINE', 'TEST_CHANGE_FILE', 'TEST_ADD_CODE_LINE', 'TEST_DEL_CODE_LINE', 'TEST_MOD_CODE_LINE', 'TEST_ADD_COMMENT_LINE', 'TEST_DEL_COMMENT_LINE', 'TEST_MOD_COMMENT_LINE', 'TEST_ADD_OTHER_LINE', 'TEST_DEL_OTHER_LINE', 'TEST_MOD_OTHER_LINE', 'BUILD_CHANGE_FILE', 'BUILD_ADD_LINE', 'BUILD_DEL_LINE', 'BUILD_MOD_LINE', 'DOC_CHANGE_FILE', 'DOC_ADD_LINE', 'DOC_DEL_LINE', 'DOC_MOD_LINE', 'OTHER_CHANGE_FILE', 'OTHER_ADD_LINE', 'OTHER_DEL_LINE', 'OTHER_MOD_LINE', 'commit_sha'],
    num_rows: 54
})

In [11]:
len(train)

30

In [12]:
train['label'].value_counts()

label
0    10
1    10
2    10
Name: count, dtype: int64

In [13]:
test['label'].value_counts()

label
2    155
0     51
1     32
Name: count, dtype: int64

In [14]:
len(train_dataset)

54

In [15]:
from sklearn import  metrics

def compute_metrics(y_pred, y_test):
    # print(y_pred,y_test)
    # classification_report = metrics.classification_report(y_test,y_pred)
    accuracy_score = metrics.accuracy_score(y_test,y_pred)
    precision_score = metrics.precision_score(y_test,y_pred, average='macro')
    recall_score = metrics.recall_score(y_test,y_pred,average='macro')
    f1_score = metrics.f1_score(y_test,y_pred,average='macro')
    
    # 混淆矩阵
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:\n", cm)
    print(metrics.classification_report(y_test, y_pred, digits=4))
    # return {"classification_report": classification_report}
    return {"classification_report":metrics.classification_report(y_test, y_pred, digits=4),"Confusion Matrix":cm,"precision": round(precision_score, 4),"recall": round(recall_score, 4), "f1":round(f1_score, 4), "accuracy": round(accuracy_score, 4)}

In [16]:
train_dataset

Dataset({
    features: ['label', 'diffs', 'text', 'CODE_CHANGE_FILE', 'CODE_ADD_CODE_LINE', 'CODE_DEL_CODE_LINE', 'CODE_MOD_CODE_LINE', 'CODE_ADD_COMMENT_LINE', 'CODE_DEL_COMMENT_LINE', 'CODE_MOD_COMMENT_LINE', 'TEST_CHANGE_FILE', 'TEST_ADD_CODE_LINE', 'TEST_DEL_CODE_LINE', 'TEST_MOD_CODE_LINE', 'TEST_ADD_COMMENT_LINE', 'TEST_DEL_COMMENT_LINE', 'TEST_MOD_COMMENT_LINE', 'TEST_ADD_OTHER_LINE', 'TEST_DEL_OTHER_LINE', 'TEST_MOD_OTHER_LINE', 'BUILD_CHANGE_FILE', 'BUILD_ADD_LINE', 'BUILD_DEL_LINE', 'BUILD_MOD_LINE', 'DOC_CHANGE_FILE', 'DOC_ADD_LINE', 'DOC_DEL_LINE', 'DOC_MOD_LINE', 'OTHER_CHANGE_FILE', 'OTHER_ADD_LINE', 'OTHER_DEL_LINE', 'OTHER_MOD_LINE', 'commit_sha'],
    num_rows: 54
})

In [17]:
train

label  \
commit_sha                                        
a2479f46f3d05b37254ad701b6b76f84624d3cb5      0   
6662fe7b185aab29aa4b2c5e08784e9da75bc700      0   
177f1fc5dd489e90eb1c4cf055e342fbc4f6ef32      0   
ec7be48470e42472a07572b7f1ca2abc91bfdad3      0   
daf4c358f7d382e7fc0466b06e3c528d24b3f760      0   
8f6f8820686cc57ab0ee3139c4d7d7c2c13b7014      0   
ca2f1678d75d9d42867f2124fa3e7dfcf1c367f7      0   
33a4df8008ce138106a71b047ddef3ba57a0a28b      0   
0c7236b292a77e330710994417c4214475fb6880      0   
7b48138ad0afc11d1ebbaa86095127e8384d6d42      0   
ed09b4ea6a17566b546a9d3ae76876636710c6a0      1   
e67010b5e2eaa5a5ddb756d7ddc2dd0194f09a0a      1   
74066765bb8ca85864f75bde6091f96207f988cf      1   
8d9e4345207013c55a8719995ec4ad4e9be466f2      1   
145c46ff3630e55b6c50ff479f54661ef54124bd      1   
73890f31af5f1247c1f5b8131f136d1045d6b5f6      1   
e6132809d27164077c2bca7f4cebdcea5e03eff0      1   
98a24828255cde13eaee893eafc9a049bb2183a7      1   
3e714ddd9f062e534c1ee028ac8b2269a062004b      1   
f64233fb2d9bcb77e9249d3bc497fd9d110e6a9f      1   
de7140853140029a3f48600b60e700464e7662b5      2   
bf0b0a30e02d7a70e092f290680b941610d9cccc      2   
b64e5919715f8dee546fbfc5049f8ec1574c2567      2   
106bcb73bcfe1c3887795a6fa2b106c665df3d56      2   
f73d059d80af7028531a12d76fb37fe4ea01254f      2   
cabba0f15882317a5bf891b92e596b32761a13ca      2   
d8cb44036919a264c55f919609f208911a348de1      2   
d37a9319ecd1723c7d50d63a87fb0d3b12a8f915      2   
c48586de08c678b506f74d5a394baf3a8d15256a      2   
7c02152e1ed348789f249d1755918721a7b22333      2   

                                                                                      diffs  \
commit_sha                                                                                    
a2479f46f3d05b37254ad701b6b76f84624d3cb5  diff --git a/django/contrib/auth/migrations/00...   
6662fe7b185aab29aa4b2c5e08784e9da75bc700  diff --git a/stb_truetype.h b/stb_truetype.h\n...   
177f1fc5dd489e90eb1c4cf055e342fbc4f6ef32  diff --git a/src/component/toolbox/feature/Sav...   
ec7be48470e42472a07572b7f1ca2abc91bfdad3  diff --git a/src/controllers/controller.scatte...   
daf4c358f7d382e7fc0466b06e3c528d24b3f760  diff --git a/library/packaging/pip b/library/p...   
8f6f8820686cc57ab0ee3139c4d7d7c2c13b7014  diff --git a/src/elements/element.point.js b/s...   
ca2f1678d75d9d42867f2124fa3e7dfcf1c367f7  diff --git a/CHANGES.txt b/CHANGES.txt\nindex ...   
33a4df8008ce138106a71b047ddef3ba57a0a28b  diff --git a/crates/bevy_text/src/lib.rs b/cra...   
0c7236b292a77e330710994417c4214475fb6880  diff --git a/lib/axios.js b/lib/axios.js\ninde...   
7b48138ad0afc11d1ebbaa86095127e8384d6d42  diff --git a/adapters/outbound/base.go b/adapt...   
ed09b4ea6a17566b546a9d3ae76876636710c6a0  diff --git a/common/net/json/host.go b/common/...   
e67010b5e2eaa5a5ddb756d7ddc2dd0194f09a0a  diff --git a/cli/file_fetcher.rs b/cli/file_fe...   
74066765bb8ca85864f75bde6091f96207f988cf  diff --git a/src/main/java/org/apache/hadoop/h...   
8d9e4345207013c55a8719995ec4ad4e9be466f2  diff --git a/truststore_nss.go b/truststore_ns...   
145c46ff3630e55b6c50ff479f54661ef54124bd  diff --git a/lib/dependencies/DelegatedExports...   
73890f31af5f1247c1f5b8131f136d1045d6b5f6  diff --git a/.goreleaser.yml b/.goreleaser.yml...   
e6132809d27164077c2bca7f4cebdcea5e03eff0  diff --git a/src/api/core/organizations.rs b/s...   
98a24828255cde13eaee893eafc9a049bb2183a7  diff --git a/src/test/java/org/elasticsearch/t...   
3e714ddd9f062e534c1ee028ac8b2269a062004b  diff --git a/platform-resources/src/META-INF/X...   
f64233fb2d9bcb77e9249d3bc497fd9d110e6a9f  diff --git a/src/main/java/rx/Single.java b/sr...   
de7140853140029a3f48600b60e700464e7662b5  diff --git a/packages/plugin-legacy/index.js b...   
bf0b0a30e02d7a70e092f290680b941610d9cccc  diff --git a/api/openapi.yml b/api/openapi.yml...   
b64e5919715f8dee546fbfc5049f8ec1574c2567  diff --git a/keras/layers/recurrent.py b/keras...   
106bcb73bcfe1c3887795a6fa2b106c665

In [18]:
model_id = "../../sentence-transformers/paraphrase-mpnet-base-v2"

In [19]:
def hp_space(trial: Trial) -> Dict[str, Union[float, int, str]]:
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-3, log=True),
        # "num_epochs": trial.suggest_int("num_epochs", 1, 3),
        # "batch_size": trial.suggest_categorical("batch_size", [8, 12, 16]),
        # "seed": trial.suggest_int("seed", 1, 40),
        # "num_iterations": trial.suggest_int("num_iterations", 10, 20),
        # "solver": trial.suggest_categorical("solver", ["newton-cg", "lbfgs", "liblinear"]),
    }
def model_init(params: Dict[str, Any]) -> CommitFitModel:
    params = params or {}
    # learning_rate = params.get("learning_rate")
    # num_iterations = params.get("num_iterations", 20)
    # solver = params.get("solver", "liblinear")
    # params = {
    #     "head_params": {
    #         # "max_iter": num_iterations,
    #         # "solver": solver,
    #     }
    # }
    return CommitFitModel.from_pretrained(model_id, **params)
def my_compute_objective(metrics):
    print('+++++++++++',metrics)
    return  metrics['accuracy']

In [ ]:
trainer = CommitFitTrainer(
    train_dataset=train_dataset,
    train_code_change = train_code_change,
    test_code_change = test_code_change,
    eval_dataset=test_dataset,
    model_init=model_init,
    metric = compute_metrics,
    num_iterations=20,
    num_epochs=10,
    batch_size = 32
)
best_run = trainer.hyperparameter_search(direction="maximize", hp_space=hp_space, compute_objective=my_compute_objective, n_trials=5)

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
[I 2025-12-11 16:46:57,532] A new study created in memory with name: no-name-93952a97-19f9-4157-8c89-bb3c52c80db5
Trial: {'learning_rate': 2.39712736345752e-06}
model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 16:48:58,320] Trial 0 finished with value: 0.5294 and parameters: {'learning_rate': 2.39712736345752e-06}. Best is trial 0 with value: 0.5294.
Trial: {'learning_rate': 5.247947416264437e-06}


Confusion Matrix:
 [[38  4  9]
 [ 1 21 10]
 [35 53 67]]
              precision    recall  f1-score   support

           0     0.5135    0.7451    0.6080        51
           1     0.2692    0.6562    0.3818        32
           2     0.7791    0.4323    0.5560       155

    accuracy                         0.5294       238
   macro avg     0.5206    0.6112    0.5153       238
weighted avg     0.6536    0.5294    0.5437       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5135    0.7451    0.6080        51\n           1     0.2692    0.6562    0.3818        32\n           2     0.7791    0.4323    0.5560       155\n\n    accuracy                         0.5294       238\n   macro avg     0.5206    0.6112    0.5153       238\nweighted avg     0.6536    0.5294    0.5437       238\n', 'Confusion Matrix': array([[38,  4,  9],
       [ 1, 21, 10],
       [35, 53, 67]]), 'precision': 0.5206, 'recall': 0.6112, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 16:50:58,785] Trial 1 finished with value: 0.542 and parameters: {'learning_rate': 5.247947416264437e-06}. Best is trial 1 with value: 0.542.
Trial: {'learning_rate': 3.4175750884988706e-05}


Confusion Matrix:
 [[42  3  6]
 [ 1 23  8]
 [37 54 64]]
              precision    recall  f1-score   support

           0     0.5250    0.8235    0.6412        51
           1     0.2875    0.7188    0.4107        32
           2     0.8205    0.4129    0.5494       155

    accuracy                         0.5420       238
   macro avg     0.5443    0.6517    0.5338       238
weighted avg     0.6855    0.5420    0.5504       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5250    0.8235    0.6412        51\n           1     0.2875    0.7188    0.4107        32\n           2     0.8205    0.4129    0.5494       155\n\n    accuracy                         0.5420       238\n   macro avg     0.5443    0.6517    0.5338       238\nweighted avg     0.6855    0.5420    0.5504       238\n', 'Confusion Matrix': array([[42,  3,  6],
       [ 1, 23,  8],
       [37, 54, 64]]), 'precision': 0.5443, 'recall': 0.6517, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 16:52:58,927] Trial 2 finished with value: 0.542 and parameters: {'learning_rate': 3.4175750884988706e-05}. Best is trial 1 with value: 0.542.
Trial: {'learning_rate': 4.433561901144278e-05}


Confusion Matrix:
 [[43  5  3]
 [ 1 26  5]
 [38 57 60]]
              precision    recall  f1-score   support

           0     0.5244    0.8431    0.6466        51
           1     0.2955    0.8125    0.4333        32
           2     0.8824    0.3871    0.5381       155

    accuracy                         0.5420       238
   macro avg     0.5674    0.6809    0.5394       238
weighted avg     0.7267    0.5420    0.5473       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5244    0.8431    0.6466        51\n           1     0.2955    0.8125    0.4333        32\n           2     0.8824    0.3871    0.5381       155\n\n    accuracy                         0.5420       238\n   macro avg     0.5674    0.6809    0.5394       238\nweighted avg     0.7267    0.5420    0.5473       238\n', 'Confusion Matrix': array([[43,  5,  3],
       [ 1, 26,  5],
       [38, 57, 60]]), 'precision': 0.5674, 'recall': 0.6809, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-11 16:55:00,966] Trial 3 finished with value: 0.5378 and parameters: {'learning_rate': 4.433561901144278e-05}. Best is trial 1 with value: 0.542.
Trial: {'learning_rate': 1.8013351456073651e-06}


Confusion Matrix:
 [[44  4  3]
 [ 1 26  5]
 [37 60 58]]
              precision    recall  f1-score   support

           0     0.5366    0.8627    0.6617        51
           1     0.2889    0.8125    0.4262        32
           2     0.8788    0.3742    0.5249       155

    accuracy                         0.5378       238
   macro avg     0.5681    0.6831    0.5376       238
weighted avg     0.7261    0.5378    0.5409       238

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5366    0.8627    0.6617        51\n           1     0.2889    0.8125    0.4262        32\n           2     0.8788    0.3742    0.5249       155\n\n    accuracy                         0.5378       238\n   macro avg     0.5681    0.6831    0.5376       238\nweighted avg     0.7261    0.5378    0.5409       238\n', 'Confusion Matrix': array([[44,  4,  3],
       [ 1, 26,  5],
       [37, 60, 58]]), 'precision': 0.5681, 'recall': 0.6831, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 2160
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 32


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

In [ ]:
best_run

In [ ]:
best_run.hyperparameters

In [23]:
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

In [24]:
fewshot_metrics = trainer.evaluate()
fewshot_metrics

***** Running evaluation *****


Confusion Matrix:
 [[42  3  6]
 [ 2 22  8]
 [39 55 61]]
              precision    recall  f1-score   support

           0     0.5060    0.8235    0.6269        51
           1     0.2750    0.6875    0.3929        32
           2     0.8133    0.3935    0.5304       155

    accuracy                         0.5252       238
   macro avg     0.5315    0.6349    0.5167       238
weighted avg     0.6751    0.5252    0.5326       238



{'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5060    0.8235    0.6269        51\n           1     0.2750    0.6875    0.3929        32\n           2     0.8133    0.3935    0.5304       155\n\n    accuracy                         0.5252       238\n   macro avg     0.5315    0.6349    0.5167       238\nweighted avg     0.6751    0.5252    0.5326       238\n',
 'Confusion Matrix': array([[42,  3,  6],
        [ 2, 22,  8],
        [39, 55, 61]]),
 'precision': 0.5315,
 'recall': 0.6349,
 'f1': 0.5167,
 'accuracy': 0.5252}

In [25]:
#发送多种类型的邮件
from email.mime.multipart import MIMEMultipart
import smtplib

from email.mime.text import MIMEText
msg_from = '915803745@qq.com'  # 发送方邮箱
passwd = 'vcuosuurrgkfbdai'   #就是上面的授权码
 
# to= ['g.zhang@gotion.com', 'j.tong@gotion.com'] #接受方邮箱
to= ['j.tong@gotion.com'] #接受方邮箱
#设置邮件内容
#MIMEMultipart类可以放任何内容
msg = MIMEMultipart()
conntent=f"{fewshot_metrics}"
#把内容加进去
msg.attach(MIMEText(conntent,'plain','utf-8'))
 
#设置邮件主题
msg['Subject']="强化学习模型训练完毕"
 
#发送方信息
msg['From']=msg_from
 
#开始发送
 
#通过SSL方式发送，服务器地址和端口
s = smtplib.SMTP_SSL("smtp.qq.com", 465)
# 登录邮箱
s.login(msg_from, passwd)
#开始发送
s.sendmail(msg_from,to,msg.as_string())
print("强化学习模型训练完毕")

强化学习模型训练完毕
