In [1]:
# !pip install transformers accelerate
from transformers import EarlyStoppingCallback
import torch
import numpy as np
import pandas as pd
# !pip install datasets
from datasets import Dataset
# %pip install evaluate
import evaluate
from sklearn.model_selection import train_test_split
# from ipywidgets import FloatProgress
import csv
from optuna import Trial
from typing import Dict, Union, Any
import os
import sys

# notebook_login()

csv.field_size_limit(500 * 1024 * 1024)
CUDA_LAUNCH_BLOCKING=1
# get pwd
notebook_path = os.path.abspath('')

# Find the part of the path that contains 'commitFit'
commit_fit_path = None
for part in notebook_path.split(os.sep):
    print(part)
    if 'CommitFit' in part:
        commit_fit_path = notebook_path.split(part)[0] + part
        break

if commit_fit_path is None:
    raise ValueError("Path containing 'commitFit' not found in notebook path.")

# Add commitFit directory to Python path, so we can import moudule from commitfit folder directly
if commit_fit_path not in sys.path:
    sys.path.append(commit_fit_path)

from commitfit import CommitFitModel, CommitFitTrainer 
from commitfit import get_templated_dataset,sample_dataset


root
autodl-tmp
CommitFit


In [19]:
df = pd.read_csv(r'/root/autodl-tmp/CommitFit/dataset/Ghadhab/dataset.csv', index_col=0, encoding='utf_8_sig')
# df.fillna('', inplace=True)
label2id={'Perfective':0, 'Adaptive':1, 'Corrective':2}
df = df.rename(columns={'labels':'labels','msgs':'msgs','commit_diff':'commit_diff'})
# df = df.replace({"maintenance_type": label2id})
# # print(df)
df
# test_sample = df.sample(n=3, random_state=1)

repo                                    commit  \
user                                                                     
ponsonio              RxJava  0531b8bff5c14d9504beefb4ad47f473e3a22932   
ponsonio              RxJava  0950c46beda335819928585f1262dfe1dca78a0b   
ponsonio              RxJava  0f92fdd8e6422d5b79c610a7fd8409d222315a49   
ponsonio              RxJava  100f571c9a2835d5a30a55374b9be74c147e031f   
ponsonio              RxJava  191f023cf5253ea90647bc091dcaf55ccdce81cc   
...                      ...                                       ...   
jenkinsci   clearcase-plugin  51e9da224f80254476a7dc446bca817b505381d8   
jexp            batch-import  609d6c4b1eea2c33d9fb950fcbb9ba9dc1f80fc3   
hdiv                    hdiv  19b650c78a1c76f4fd90274d7f163f863c0d39e4   
casidiablo       persistence  d7bf95159df37a3d338ca267dddd3d26b38ec37c   
jhy                    jsoup  d6fd1637307f6b088eb226c3f979085725530f32   

                labels                                               msgs  \
user                                                                        
ponsonio    Perfective              Change hasException to hasThrowable--   
ponsonio      Adaptive  Trying to extend the Scheduler interface accor...   
ponsonio      Adaptive   RunAsync method for outputting multiple values--   
ponsonio    Corrective  forEach with Action1 but not Observer--I re-re...   
ponsonio    Corrective  1.x: Fix Completable swallows- OnErrorNotImple...   
...                ...                                                ...   
jenkinsci   Perfective  Use a temporary file to decrease memory consum...   
jexp        Perfective  added a more memory efficient structure for st...   
hdiv        Perfective               Memory and performance optimizations   
casidiablo  Perfective  Now it is possible to specify the sqlite open ...   
jhy         Perfective            Performance improvment for Element.text   

                                                        diffs  \
user                                                            
ponsonio    diff --git a/rxjava-core/src/main/java/rx/Noti...   
ponsonio    diff --git a/rxjava-core/src/main/java/rx/Sche...   
ponsonio    diff --git a/rxjava-contrib/rxjava-async-util/...   
ponsonio    diff --git a/language-adaptors/rxjava-groovy/s...   
ponsonio    diff --git a/src/main/java/rx/Completable.java...   
...                                                       ...   
jenkinsci   diff --git a/src/main/java/hudson/plugins/clea...   
jexp        diff --git a/src/main/java/org/neo4j/batchimpo...   
hdiv        diff --git a/hdiv-config/src/main/java/org/hdi...   
casidiablo  diff --git a/pom.xml b/pom.xml\nindex 394263b....   
jhy         diff --git a/src/main/java/org/jsoup/helper/St...   

                                                      feature  
user                                                           
ponsonio    [1, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
ponsonio    [2, 44, 0, 0, 30, 0, 0, 1, 18, 0, 0, 0, 0, 0, ...  
ponsonio    [2, 53, 0, 0, 42, 0, 0, 1, 45, 1, 0, 0, 0, 0, ...  
ponsonio    [1, 5, 122, 9, 10, 9, 4, 1, 5, 18, 2, 0, 0, 0,...  
ponsonio    [1, 1, 0, 0, 0, 0, 0, 1, 21, 0, 0, 0, 0, 0, 0,...  
...                                                       ...  
jenkinsci   [2, 12, 0, 4, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,...  
jexp        [10, 159, 29, 35, 9, 2, 1, 5, 106, 0, 4, 8, 0,...  
hdiv        [31, 302, 131, 140, 170, 89, 53, 7, 88, 14, 17...  
casidiablo  [5, 57, 20, 9, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
jhy         [3, 11, 11, 9, 13, 0, 0, 1, 0, 8, 0, 0, 1, 0, ...  

[1781 rows x 6 columns]

In [20]:
train, temp_df = train_test_split(df, test_size=0.3, random_state=42)
val, test = train_test_split(temp_df, test_size=0.5, random_state=42)

In [21]:
train = train.groupby("labels", group_keys=False).apply(lambda x: x.sample(n=1, random_state=42))

/tmp/ipykernel_1442/2953279344.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train = train.groupby("labels", group_keys=False).apply(lambda x: x.sample(n=1, random_state=42))


In [23]:
# train.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/5_train.csv')
# test.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/test.csv')
# val.to_csv('/root/autodl-tmp/CommitFit/dataset/Ghadhab/val.csv')

train.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/1_train.csv')
test.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/test.csv')
val.to_csv('/root/autodl-tmp/COLARE-main/dataset/Ghadhab/val.csv')

In [6]:
Dataset_train = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

In [7]:
train_dataset = get_templated_dataset(Dataset_train, candidate_labels=['Corrective','Adaptive','Perfective'], sample_size=8)

In [8]:
train_code_change = list(train['diffs'].astype(str))
test_code_change = list(test['diffs'].astype(str))

In [9]:
# list(train['message'].astype(str).values)
train_dataset

Dataset({
    features: ['repo', 'commit', 'label', 'text', 'diffs', 'feature', 'user'],
    num_rows: 27
})

In [10]:
len(train)

3

In [11]:
train['label'].value_counts()

label
0    1
1    1
2    1
Name: count, dtype: int64

In [12]:
test['label'].value_counts()

label
0    100
2     89
1     79
Name: count, dtype: int64

In [13]:
len(train_dataset)

27

In [14]:
from sklearn import  metrics

def compute_metrics(y_pred, y_test):
    # print(y_pred,y_test)
    # classification_report = metrics.classification_report(y_test,y_pred)
    accuracy_score = metrics.accuracy_score(y_test,y_pred)
    precision_score = metrics.precision_score(y_test,y_pred, average='macro')
    recall_score = metrics.recall_score(y_test,y_pred,average='macro')
    f1_score = metrics.f1_score(y_test,y_pred,average='macro')
    
    # 混淆矩阵
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:\n", cm)
    print(metrics.classification_report(y_test, y_pred, digits=4))
    # return {"classification_report": classification_report}
    return {"classification_report":metrics.classification_report(y_test, y_pred, digits=4),"Confusion Matrix":cm,"precision": round(precision_score, 4),"recall": round(recall_score, 4), "f1":round(f1_score, 4), "accuracy": round(accuracy_score, 4)}

In [15]:
train_dataset

Dataset({
    features: ['repo', 'commit', 'label', 'text', 'diffs', 'feature', 'user'],
    num_rows: 27
})

In [16]:
model_id = "../../sentence-transformers/paraphrase-mpnet-base-v2"

In [17]:
def hp_space(trial: Trial) -> Dict[str, Union[float, int, str]]:
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-3, log=True),
        # "num_epochs": trial.suggest_int("num_epochs", 1, 3),
        # "batch_size": trial.suggest_categorical("batch_size", [8, 12, 16]),
        # "seed": trial.suggest_int("seed", 1, 40),
        # "num_iterations": trial.suggest_int("num_iterations", 10, 20),
        # "solver": trial.suggest_categorical("solver", ["newton-cg", "lbfgs", "liblinear"]),
    }
def model_init(params: Dict[str, Any]) -> CommitFitModel:
    params = params or {}
    # learning_rate = params.get("learning_rate")
    # num_iterations = params.get("num_iterations", 20)
    # solver = params.get("solver", "liblinear")
    # params = {
    #     "head_params": {
    #         # "max_iter": num_iterations,
    #         # "solver": solver,
    #     }
    # }
    return CommitFitModel.from_pretrained(model_id, **params)
def my_compute_objective(metrics):
    print('+++++++++++',metrics)
    return  metrics['accuracy']

In [18]:
trainer = CommitFitTrainer(
    train_dataset=train_dataset,
    train_code_change = train_code_change,
    test_code_change = test_code_change,
    eval_dataset=test_dataset,
    model_init=model_init,
    metric = compute_metrics,
    num_iterations=20,
    num_epochs=10
)
best_run = trainer.hyperparameter_search(direction="maximize", hp_space=hp_space, compute_objective=my_compute_objective, n_trials=10)

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
[I 2025-12-10 20:19:42,458] A new study created in memory with name: no-name-7282d0c4-375c-471f-8ae2-b3cb59067a77
Trial: {'learning_rate': 0.00022876850002660502}
model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:20:30,952] Trial 0 finished with value: 0.5037 and parameters: {'learning_rate': 0.00022876850002660502}. Best is trial 0 with value: 0.5037.
Trial: {'learning_rate': 6.923962956831083e-06}


Confusion Matrix:
 [[25 50 25]
 [10 54 15]
 [ 9 24 56]]
              precision    recall  f1-score   support

           0     0.5682    0.2500    0.3472       100
           1     0.4219    0.6835    0.5217        79
           2     0.5833    0.6292    0.6054        89

    accuracy                         0.5037       268
   macro avg     0.5245    0.5209    0.4915       268
weighted avg     0.5301    0.5037    0.4844       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5682    0.2500    0.3472       100\n           1     0.4219    0.6835    0.5217        79\n           2     0.5833    0.6292    0.6054        89\n\n    accuracy                         0.5037       268\n   macro avg     0.5245    0.5209    0.4915       268\nweighted avg     0.5301    0.5037    0.4844       268\n', 'Confusion Matrix': array([[25, 50, 25],
       [10, 54, 15],
       [ 9, 24, 56]]), 'precision': 0.5245, 'recall': 0.5209, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:21:18,137] Trial 1 finished with value: 0.5373 and parameters: {'learning_rate': 6.923962956831083e-06}. Best is trial 1 with value: 0.5373.
Trial: {'learning_rate': 0.00012270552545332159}


Confusion Matrix:
 [[33 26 41]
 [12 43 24]
 [12  9 68]]
              precision    recall  f1-score   support

           0     0.5789    0.3300    0.4204       100
           1     0.5513    0.5443    0.5478        79
           2     0.5113    0.7640    0.6126        89

    accuracy                         0.5373       268
   macro avg     0.5472    0.5461    0.5269       268
weighted avg     0.5483    0.5373    0.5218       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5789    0.3300    0.4204       100\n           1     0.5513    0.5443    0.5478        79\n           2     0.5113    0.7640    0.6126        89\n\n    accuracy                         0.5373       268\n   macro avg     0.5472    0.5461    0.5269       268\nweighted avg     0.5483    0.5373    0.5218       268\n', 'Confusion Matrix': array([[33, 26, 41],
       [12, 43, 24],
       [12,  9, 68]]), 'precision': 0.5472, 'recall': 0.5461, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:22:06,245] Trial 2 finished with value: 0.5224 and parameters: {'learning_rate': 0.00012270552545332159}. Best is trial 1 with value: 0.5373.
Trial: {'learning_rate': 5.9341661147002807e-05}


Confusion Matrix:
 [[36 36 28]
 [18 42 19]
 [15 12 62]]
              precision    recall  f1-score   support

           0     0.5217    0.3600    0.4260       100
           1     0.4667    0.5316    0.4970        79
           2     0.5688    0.6966    0.6263        89

    accuracy                         0.5224       268
   macro avg     0.5191    0.5294    0.5164       268
weighted avg     0.5211    0.5224    0.5135       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5217    0.3600    0.4260       100\n           1     0.4667    0.5316    0.4970        79\n           2     0.5688    0.6966    0.6263        89\n\n    accuracy                         0.5224       268\n   macro avg     0.5191    0.5294    0.5164       268\nweighted avg     0.5211    0.5224    0.5135       268\n', 'Confusion Matrix': array([[36, 36, 28],
       [18, 42, 19],
       [15, 12, 62]]), 'precision': 0.5191, 'recall': 0.5294, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:22:53,995] Trial 3 finished with value: 0.5448 and parameters: {'learning_rate': 5.9341661147002807e-05}. Best is trial 3 with value: 0.5448.
Trial: {'learning_rate': 0.0003595801354594296}


Confusion Matrix:
 [[32 35 33]
 [12 49 18]
 [10 14 65]]
              precision    recall  f1-score   support

           0     0.5926    0.3200    0.4156       100
           1     0.5000    0.6203    0.5537        79
           2     0.5603    0.7303    0.6341        89

    accuracy                         0.5448       268
   macro avg     0.5510    0.5569    0.5345       268
weighted avg     0.5546    0.5448    0.5289       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5926    0.3200    0.4156       100\n           1     0.5000    0.6203    0.5537        79\n           2     0.5603    0.7303    0.6341        89\n\n    accuracy                         0.5448       268\n   macro avg     0.5510    0.5569    0.5345       268\nweighted avg     0.5546    0.5448    0.5289       268\n', 'Confusion Matrix': array([[32, 35, 33],
       [12, 49, 18],
       [10, 14, 65]]), 'precision': 0.551, 'recall': 0.5569, 'f1': 0.5

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:23:41,369] Trial 4 finished with value: 0.4664 and parameters: {'learning_rate': 0.0003595801354594296}. Best is trial 3 with value: 0.5448.
Trial: {'learning_rate': 3.6132152903978784e-05}


Confusion Matrix:
 [[26 57 17]
 [17 58  4]
 [15 33 41]]
              precision    recall  f1-score   support

           0     0.4483    0.2600    0.3291       100
           1     0.3919    0.7342    0.5110        79
           2     0.6613    0.4607    0.5430        89

    accuracy                         0.4664       268
   macro avg     0.5005    0.4850    0.4611       268
weighted avg     0.5024    0.4664    0.4538       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4483    0.2600    0.3291       100\n           1     0.3919    0.7342    0.5110        79\n           2     0.6613    0.4607    0.5430        89\n\n    accuracy                         0.4664       268\n   macro avg     0.5005    0.4850    0.4611       268\nweighted avg     0.5024    0.4664    0.4538       268\n', 'Confusion Matrix': array([[26, 57, 17],
       [17, 58,  4],
       [15, 33, 41]]), 'precision': 0.5005, 'recall': 0.485, 'f1': 0.4

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:24:28,777] Trial 5 finished with value: 0.556 and parameters: {'learning_rate': 3.6132152903978784e-05}. Best is trial 5 with value: 0.556.
Trial: {'learning_rate': 3.5643931242029463e-06}


Confusion Matrix:
 [[32 34 34]
 [10 50 19]
 [10 12 67]]
              precision    recall  f1-score   support

           0     0.6154    0.3200    0.4211       100
           1     0.5208    0.6329    0.5714        79
           2     0.5583    0.7528    0.6411        89

    accuracy                         0.5560       268
   macro avg     0.5649    0.5686    0.5445       268
weighted avg     0.5686    0.5560    0.5385       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.6154    0.3200    0.4211       100\n           1     0.5208    0.6329    0.5714        79\n           2     0.5583    0.7528    0.6411        89\n\n    accuracy                         0.5560       268\n   macro avg     0.5649    0.5686    0.5445       268\nweighted avg     0.5686    0.5560    0.5385       268\n', 'Confusion Matrix': array([[32, 34, 34],
       [10, 50, 19],
       [10, 12, 67]]), 'precision': 0.5649, 'recall': 0.5686, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:25:17,108] Trial 6 finished with value: 0.5373 and parameters: {'learning_rate': 3.5643931242029463e-06}. Best is trial 5 with value: 0.556.
Trial: {'learning_rate': 0.000527594279215287}


Confusion Matrix:
 [[32 26 42]
 [11 44 24]
 [12  9 68]]
              precision    recall  f1-score   support

           0     0.5818    0.3200    0.4129       100
           1     0.5570    0.5570    0.5570        79
           2     0.5075    0.7640    0.6099        89

    accuracy                         0.5373       268
   macro avg     0.5487    0.5470    0.5266       268
weighted avg     0.5498    0.5373    0.5208       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5818    0.3200    0.4129       100\n           1     0.5570    0.5570    0.5570        79\n           2     0.5075    0.7640    0.6099        89\n\n    accuracy                         0.5373       268\n   macro avg     0.5487    0.5470    0.5266       268\nweighted avg     0.5498    0.5373    0.5208       268\n', 'Confusion Matrix': array([[32, 26, 42],
       [11, 44, 24],
       [12,  9, 68]]), 'precision': 0.5487, 'recall': 0.547, 'f1': 0.5

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:26:04,757] Trial 7 finished with value: 0.4776 and parameters: {'learning_rate': 0.000527594279215287}. Best is trial 5 with value: 0.556.
Trial: {'learning_rate': 0.0006906892224280655}


Confusion Matrix:
 [[26 58 16]
 [14 59  6]
 [12 34 43]]
              precision    recall  f1-score   support

           0     0.5000    0.2600    0.3421       100
           1     0.3907    0.7468    0.5130        79
           2     0.6615    0.4831    0.5584        89

    accuracy                         0.4776       268
   macro avg     0.5174    0.4967    0.4712       268
weighted avg     0.5214    0.4776    0.4643       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5000    0.2600    0.3421       100\n           1     0.3907    0.7468    0.5130        79\n           2     0.6615    0.4831    0.5584        89\n\n    accuracy                         0.4776       268\n   macro avg     0.5174    0.4967    0.4712       268\nweighted avg     0.5214    0.4776    0.4643       268\n', 'Confusion Matrix': array([[26, 58, 16],
       [14, 59,  6],
       [12, 34, 43]]), 'precision': 0.5174, 'recall': 0.4967, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:26:52,874] Trial 8 finished with value: 0.4701 and parameters: {'learning_rate': 0.0006906892224280655}. Best is trial 5 with value: 0.556.
Trial: {'learning_rate': 1.1330104495283185e-06}


Confusion Matrix:
 [[39 35 26]
 [29 40 10]
 [21 21 47]]
              precision    recall  f1-score   support

           0     0.4382    0.3900    0.4127       100
           1     0.4167    0.5063    0.4571        79
           2     0.5663    0.5281    0.5465        89

    accuracy                         0.4701       268
   macro avg     0.4737    0.4748    0.4721       268
weighted avg     0.4744    0.4701    0.4702       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.4382    0.3900    0.4127       100\n           1     0.4167    0.5063    0.4571        79\n           2     0.5663    0.5281    0.5465        89\n\n    accuracy                         0.4701       268\n   macro avg     0.4737    0.4748    0.4721       268\nweighted avg     0.4744    0.4701    0.4702       268\n', 'Confusion Matrix': array([[39, 35, 26],
       [29, 40, 10],
       [21, 21, 47]]), 'precision': 0.4737, 'recall': 0.4748, 'f1': 0.

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

***** Running evaluation *****
[I 2025-12-10 20:27:40,794] Trial 9 finished with value: 0.5522 and parameters: {'learning_rate': 1.1330104495283185e-06}. Best is trial 5 with value: 0.556.


Confusion Matrix:
 [[42 23 35]
 [15 43 21]
 [15 11 63]]
              precision    recall  f1-score   support

           0     0.5833    0.4200    0.4884       100
           1     0.5584    0.5443    0.5513        79
           2     0.5294    0.7079    0.6058        89

    accuracy                         0.5522       268
   macro avg     0.5571    0.5574    0.5485       268
weighted avg     0.5581    0.5522    0.5459       268

+++++++++++ {'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5833    0.4200    0.4884       100\n           1     0.5584    0.5443    0.5513        79\n           2     0.5294    0.7079    0.6058        89\n\n    accuracy                         0.5522       268\n   macro avg     0.5571    0.5574    0.5485       268\nweighted avg     0.5581    0.5522    0.5459       268\n', 'Confusion Matrix': array([[42, 23, 35],
       [15, 43, 21],
       [15, 11, 63]]), 'precision': 0.5571, 'recall': 0.5574, 'f1': 0.

In [19]:
# best_run

In [20]:
best_run.hyperparameters

{'learning_rate': 3.6132152903978784e-05}

In [21]:
trainer.apply_hyperparameters(best_run.hyperparameters, final_model=True)
trainer.train()

model_head.pkl not found in /root/autodl-tmp/CommitFit/sentence-transformers/paraphrase-mpnet-base-v2, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


Generating Training Pairs:   0%|          | 0/20 [00:00<?, ?it/s]

***** Running training *****
  Num examples = 1080
  Num epochs = 10
  Total optimization steps = 680
  Total train batch size = 16


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

Iteration:   0%|          | 0/68 [00:00<?, ?it/s]

In [22]:
fewshot_metrics = trainer.evaluate()
fewshot_metrics

***** Running evaluation *****


Confusion Matrix:
 [[29 34 37]
 [ 9 48 22]
 [11 10 68]]
              precision    recall  f1-score   support

           0     0.5918    0.2900    0.3893       100
           1     0.5217    0.6076    0.5614        79
           2     0.5354    0.7640    0.6296        89

    accuracy                         0.5410       268
   macro avg     0.5497    0.5539    0.5268       268
weighted avg     0.5524    0.5410    0.5198       268



{'classification_report': '              precision    recall  f1-score   support\n\n           0     0.5918    0.2900    0.3893       100\n           1     0.5217    0.6076    0.5614        79\n           2     0.5354    0.7640    0.6296        89\n\n    accuracy                         0.5410       268\n   macro avg     0.5497    0.5539    0.5268       268\nweighted avg     0.5524    0.5410    0.5198       268\n',
 'Confusion Matrix': array([[29, 34, 37],
        [ 9, 48, 22],
        [11, 10, 68]]),
 'precision': 0.5497,
 'recall': 0.5539,
 'f1': 0.5268,
 'accuracy': 0.541}

In [23]:
#发送多种类型的邮件
from email.mime.multipart import MIMEMultipart
import smtplib

from email.mime.text import MIMEText
msg_from = '915803745@qq.com'  # 发送方邮箱
passwd = 'vcuosuurrgkfbdai'   #就是上面的授权码
 
# to= ['g.zhang@gotion.com', 'j.tong@gotion.com'] #接受方邮箱
to= ['j.tong@gotion.com'] #接受方邮箱
#设置邮件内容
#MIMEMultipart类可以放任何内容
msg = MIMEMultipart()
conntent=f"{fewshot_metrics}"
#把内容加进去
msg.attach(MIMEText(conntent,'plain','utf-8'))
 
#设置邮件主题
msg['Subject']="强化学习模型训练完毕"
 
#发送方信息
msg['From']=msg_from
 
#开始发送
 
#通过SSL方式发送，服务器地址和端口
s = smtplib.SMTP_SSL("smtp.qq.com", 465)
# 登录邮箱
s.login(msg_from, passwd)
#开始发送
s.sendmail(msg_from,to,msg.as_string())
print("强化学习模型训练完毕")

强化学习模型训练完毕
